### ISSUE TITLE
Use a "." in parametric type JSDOC before the angle bracket

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1005]
From Dev meeting Thursday,  Jan 21, 2021

✓JB: PSA - reminder that the type specs should look like {Property.<MyType>} as opposed to {Property<MyType>}.  In other words, don’t forget the period.
priority then.
SR: I can see that it is documented as such in the code review checklist.   But my recollection was that either were acceptable, and it was developer preference.  Maybe we had a consensus and didn’t update the code review checklist?  Or am I misremembering?
JG: If strict, is it something we can search and replace and then add to bad-text.js?
MK: Google closure syntax supports no dot: https://github.com/google/closure-compiler/wiki/Generic-Types
SR: I’ll convert my cases
JB: I’ll convert my cases
MK: I’ll add an eslint rule
JB: Here's a regEx that gets them, but has a lot of false positives.  I'll refine.  \{.*[a-zA-Z]<[a-zA-Z]

Assigning people that volunteered in the thread.

**Comment by samreid** [comment]
I fixed my easy-to-discover cases, and am happy to address more if we get a better regex or lint search, self-unassigning.

**Comment by jbphet** [comment]
I searched the code base using the regular expression and found quite a few violations (note that in IntelliJ, the case-sensitivity switch should be on for this search for it to work correctly):
```
[a-z]<[A-Z][A-Za-z]+>
```

Using this, I identified common violations and did a search and replace.  These were:
- Array<
- Property<
- ObservableArrayDef<
- Map<
- PhetioGroup<
- Function<
- Promise<

I did a few more less common ones by hand, and I think I got most of them.

I did *not* do sugar-and-salt solutions because there are a ton of false positives in that sim due to the Java code having been pasted in.  This sim is no longer being maintained, so I don't think there's any issue with this.

@zepumph - @samreid assigned you too, so I think maybe you had volunteered to do your own sims.  I think I have hit most if not all cases, so I'd recommend you briefly look through what I've done and maybe try some searches of your own, and close if all looks good.

**Comment by zepumph** [comment]
I found a couple more with this regex:

`\{\w+<`


I also found that `Function.<` was being used instead of `{function():}` notation that we decided was more descriptive in dev meeting some time ago. 

Everything felt comfortable while changing except in GAO. @samreid, can you please review and alter https://github.com/phetsims/gravity-and-orbits/commit/d93d9dc2960fd1d2f4f99583cfcd2d888c11ea24, including the TODO as well as the typedoc: `ModeListParameterList`, which doesn't seem to exist anywhere else.

**Comment by zepumph** [comment]
- [ ] I also noticed that the IOTypes don't use a period. @samreid is this still what you prefer for the phet-io type api?

**Comment by samreid** [comment]
I don't think the IO types should have a dot, as determined in https://github.com/phetsims/phet-io/issues/1545

**Comment by samreid** [comment]
Thanks, I corrected the Gravity and Orbits parts in the commits.  Do we still wish to create an eslint rule for this, as mentioned in the issue description?

**Comment by zepumph** [comment]
I tested the above with something simple, like `DerivedProperty<boolean>` as well as nesting like `{Array.<something<else>>}`. It worked with no false positives in the whole project. @jbphet, anything else?

**Comment by jbphet** [comment]
Nope, should be good.  Closing.
