### ISSUE TITLE
Enable no-lone-blocks lint rule?

### ISSUE THREAD

**Issue by chrisklus** [phetsims/chipper#1026]
From discussion in https://github.com/phetsims/chipper/issues/814#issuecomment-802949806.

The dev team discussed if we should allow lone blocks in code:

```js

// some code

{ 
  // some indented code in a standalone block
  
}

// some more code
```

Many of the cases we looked at we thought were unnecessary and were being used for visual separation (which could be achieved with other standard ways like line breaks or comments), but we decided it would be nice to get input from @pixelzoom before making any decisions.

**Comment by pixelzoom** [comment]
👎🏻 Two things:

(1) This rule is yet-another example of "take a tool away because developers don't know how to use it".  I have a real problem with that. See also https://github.com/phetsims/chipper/issues/1027.

(2) I'm not clear about what's motivating this general topic. Why does PhET suddenly feels the need to enabled/examine every lint rule?  I'll be surprised if the benefit to PhET ever approaches the cost to discuss this.

That said... 

In addition to visual separation, a code block (in ES6) allows you to create a new scope.  That's a useful tool, but (like any language feature) it requires the developer to use blocks appropriately, and the reader to userstand JS scope.  A lint rule guarantees that no learning will take place in the context of a lone code block, because you won't be able use one.

https://eslint.org/docs/rules/no-lone-blocks says "This rule aims to eliminate unnecessary and potentially confusing blocks at the top level of a script or within other blocks."   It is not the case that every lone code block is "unnecessary and potentially confusing".   And I think this is probably more applicable to typical "web" code, where everything is lumped into one unstructured script.  So I see not reason to enable this rule for PhET code.

**Comment by pixelzoom** [comment]
As luck would have it, I immediately ran into a real-world example right after adding the above comment.  For https://github.com/phetsims/chipper/issues/1021, the task was to remove this usage of `var` from FaceWithPointsNode.js:

```js
      case 'rightBottom':
        var position = new Vector2( this.faceNode.right + this.spacing, this.faceNode.centerY ); // eslint-disable-line no-var
        position.rotate( Math.PI / 4 );
        this.pointsNode.left = position.x;
        this.pointsNode.centerY = position.y;
        break;
```

First attempt was to simply change `var` to `const`.  That fails lint with `153:5  error  Nested block is redundant  no-lone-blocks`:

 ```js
      case 'rightBottom':
        const position = new Vector2( this.faceNode.right + this.spacing, this.faceNode.centerY ); // eslint-disable-line no-var
        position.rotate( Math.PI / 4 );
        this.pointsNode.left = position.x;
        this.pointsNode.centerY = position.y;
        break;
```

This would work:

```js
    let position;
    switch( this.pointsAlignment ) {
...
      case 'rightBottom':
        position = new Vector2( this.faceNode.right + this.spacing, this.faceNode.centerY ); // eslint-disable-line no-var
        position.rotate( Math.PI / 4 );
        this.pointsNode.left = position.x;
        this.pointsNode.centerY = position.y;
        break;
```

But since `position` is relative only to one specific `case`, that seems like an inferior solution.   What would be more appropriate is to create a scope for the `case` statement, and define `position` is that scope.  That involves using a block, like this:

```js
      case 'rightBottom': {
        const position = new Vector2( this.faceNode.right + this.spacing, this.faceNode.centerY ); // eslint-disable-line no-var
        position.rotate( Math.PI / 4 );
        this.pointsNode.left = position.x;
        this.pointsNode.centerY = position.y;
        }
        break;
```

That of course will fail the "no-lone-blocks" rule. 

Not wanting to revist this code (or this GitHub issue), I decided togo with this solution, which eliminates the definition of `position`:

```js
      case 'rightBottom':
        this.pointsNode.leftCenter = new Vector2( this.faceNode.right + this.spacing, this.faceNode.centerY ).rotate( Math.PI / 4 );
        break;
```

That involved changing more code than I think should be necessary for a maintence change. But I'm fine with the solution that I ended up with.  And that specific solution is also not the point.   

The point is that defining a scope is sometimes an obvious, appropriate way to solve a problem.  As a developer, you need to understand scope to consider and evaluate that option.  You're more likely to know about scope if you have seen examples that explicitly create a scope.  You're not going to see those examples if the "no-lone-blocks" rule is enabled.  For developers who do know about scope, some will change the implementation rather than add a `// eslint-disable` comment.   And I have demonstrated here that I am (against my instincts) feeling the need to behave like such a developer, rather than use the right tool for the task.

**Comment by samreid** [comment]
Today's consensus was that we like using blocks in case statements, but we didn't have time to talk about this pattern:

```js
// layout
{
...
}
```

Leaving on agenda for next week.

**Comment by pixelzoom** [comment]
Re: 

```js
// layout
{
}
```

@samreid said that this "offends" some developers, and wants to discuss more.  

I think you're offended by something that you don't fully understand.  And I suspect that it comes from a fundamental misunderstanding about what a "block" is, possibly a belief that "block" == "control block".  A control blocks (`if`, `while`, etc.) is a specialization of block, not synonymous with block.   In block-structured languages (like JS), a block is **ANY** lexical grouping of one or more declarations and/or statements.  From https://en.wikipedia.org/wiki/Block_(programming), "The function of blocks in programming is to enable groups of statements to be treated as if they were one statement, and to narrow the lexical scope of objects such as variables, procedures and functions declared in a block so that they do not conflict with those having the same name used elsewhere."

This lint rule is question defines "lone-blocks" as "standalone code blocks", which means any block that is not a control block.

Re the above "layout" example specifically... A lone block is used here to group all statements related to layout. Its purpose is to (1) allowing the reader to consider this entire block as one logical statement, and (2) encourage maintainers to make "layout" modifications in this block, thus keeping related code together.  Have I used a lone block like this everywhere? No.  Does using it in one place mean I must use it everywhere or not at all. Certainly not.

So 3 questions:

* Should PhET developers know what a "block" is, understand the difference between control blocks and lone blocks, and recognize either type when they see one?  I think so.

* Should PhET developers understand the potential uses for a lone block? Again, I think so.

* Should PhET developers be required to use a lone blocks to group all related code? Certainly not. Use at your discretion.

* Should PhET ban the use of lone blocks? I'm not sure what purpose that serves, or frankly why we're spending so much time discussing it.

**Comment by pixelzoom** [comment]
If we want to talk about offensive layout code, let's have a look at WaveMeterNode.js:

```js
  constructor( model, view, options ) {
...
   this.backgroundNode = backgroundNode;
... some unrelated code
    this.addChild( this.backgroundNode );
...
      const probeNode = new WaveMeterProbeNode( view.visibleBoundsProperty, {
... some unrelated code
      this.addChild( new WireNode( connectionProperty, new Vector2Property( new Vector2( -NORMAL_DISTANCE, 0 ) ),
        new NodeProperty( probeNode, probeNode.boundsProperty, 'centerBottom' ), new Vector2Property( new Vector2( 0, NORMAL_DISTANCE ) ), {
          lineWidth: WIRE_LINE_WIDTH,
          stroke: wireColor
        }
      ) );
      this.addChild( probeNode );
```

Trying to see the rendering order here takes some work, and this is a relatively simple example with a small number of Nodes.  I see this kind of code literally everywhere, some of it much worse.  Explain why the above pattern is OK, while this is offensive and worthy of more discussion:

```
    // layout
  {
    this.addChild( this.backgroundNode );
    this.addChild( wireNode );
    this.addChild( probeNode );
  }
```

**Comment by pixelzoom** [comment]
Other example of lone blocks from the PhET code base...

migrate.js has 3 lone blocks which look very nice. For example,  in https://github.com/phetsims/chipper/commit/d2c73aeb83ffcafa9d033c9b61e37299f5e45e31, @samreid added a chunk of code with a comment at the top for "short relative imports".  In context, it's difficult to see where this logical chunk of code ends.  In https://github.com/phetsims/chipper/commit/ed5a40497abbbc81f5c58388c7a41cfac6612688, @jonathanolson cleaned this up and put hte "short relative imports" code in a lone block.  There's no additional scope needed, just a nice clean grouping of related statements that clearly shows me where "short relative imports" begins and ends.  Maybe if you thought of this as an inline alternative to a function is would be more palatable? 

FaucetNode.js has a lone block for layout (positioning subcomponents).  After 7+ years and many revisions, all of the layout code is still in that block.

Looking through the other lone blocks, I see a couple more from @jonathanolson, and the rest are mine. All of them are clearly documented with a comment that describes the block.

So...  I think that's enough from me.  I'd like to hear from @samreid. What is your objection to lone blocks? What is it that you find offensive?

**Comment by pixelzoom** [comment]
Here are the current lone blocks in the PhET code base:

```
% cd perennial
% grunt lint-everything
Running "lint-everything" task
>> (node:28696) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
>> (Use `node --trace-warnings ...` to show where the warning was created)

/Users/cmalley/PhET/GitHub/beers-law-lab/js/beerslaw/view/BeersLawScreenView.js
  85:5  error  Nested block is redundant  no-lone-blocks

/Users/cmalley/PhET/GitHub/chipper/js/grunt/migrate.js
  459:3  error  Nested block is redundant  no-lone-blocks
  494:3  error  Nested block is redundant  no-lone-blocks
  512:3  error  Nested block is redundant  no-lone-blocks

/Users/cmalley/PhET/GitHub/dot/js/SingularValueDecomposition.js
  313:17  error  Block is redundant  no-lone-blocks
  338:17  error  Block is redundant  no-lone-blocks
  427:17  error  Block is redundant  no-lone-blocks

/Users/cmalley/PhET/GitHub/graphing-lines/js/linegame/model/ChallengeFactory1.js
   87:5  error  Nested block is redundant  no-lone-blocks
  111:5  error  Nested block is redundant  no-lone-blocks

/Users/cmalley/PhET/GitHub/graphing-lines/js/linegame/model/ChallengeFactory2.js
   86:5  error  Nested block is redundant  no-lone-blocks
  109:5  error  Nested block is redundant  no-lone-blocks

/Users/cmalley/PhET/GitHub/graphing-lines/js/linegame/model/ChallengeFactory4.js
  113:5  error  Nested block is redundant  no-lone-blocks

/Users/cmalley/PhET/GitHub/graphing-lines/js/pointslope/view/PointSlopeEquationNode.js
  409:7  error  Nested block is redundant  no-lone-blocks

/Users/cmalley/PhET/GitHub/graphing-lines/js/slope/view/SlopeEquationNode.js
  162:7  error  Nested block is redundant  no-lone-blocks

/Users/cmalley/PhET/GitHub/graphing-lines/js/slopeintercept/view/SlopeInterceptEquationNode.js
  382:7  error  Nested block is redundant  no-lone-blocks

/Users/cmalley/PhET/GitHub/least-squares-regression/js/least-squares-regression/view/LeastSquaresRegressionScreenView.js
  326:5  error  Nested block is redundant  no-lone-blocks

/Users/cmalley/PhET/GitHub/scenery-phet/js/FaucetNode.js
  153:5  error  Nested block is redundant  no-lone-blocks

✖ 17 problems (17 errors, 0 warnings)

Warning: 17 errors and 0 warnings Use --force to continue.

Aborted due to warnings.
Fatal error: perennial grunt "--repo=chipper" "lint-everything" failed with code 6
```

**Comment by samreid** [comment]
> I'd like to hear from @samreid. What is your objection to lone blocks? What is it that you find offensive?

In https://github.com/phetsims/chipper/issues/814 I said:

> SR: This seems like it warrants discussion--I know we used this pattern more in Java. I don't really like the pattern but maybe others think it's effective?

I can see that you think it's effective in the right contexts, I'm glad we got your feedback before making a decision.  In the same issue @zepumph said:

> MK: I recommend we adopt [the no-lone-blocks rule]. generally seems like it wouldn't pass code review.

Finally, the developer consensus in the top comment of this file was:

> Many of the cases we looked at we thought were unnecessary and were being used for visual separation (which could be achieved with other standard ways like line breaks or comments)

Since then, and based our our discussion, I'd like to revise and clarify my position.  Generally, I think our project is stronger when we have a more uniform style, as if all our code was written by a single (amazing!) author. That is probably too lofty a goal to attain in practice, but I think it's a good philosophy.

Next, if redundant code blocks (redundant being ESLint's term, not mine) are so useful, why do we only have 17 of them across our nearly 850,000 lines of code?  Based on this rarity, they do seem "unconventional" for our project, even if they are really useful in the places where they are employed.  But unless we plan to start using them a lot more, I would still enable the rule as a reminder that this is rare for our project.  Imagine if a new developer or intern on our project misuses or employs too many redundant code blocks, ESLint could immediately let them know that it's not conventional for our project.

In today's developer meeting I indicated that I could be bothered or confused by another level of indenting.  I think that's because these are so rare, if I saw additional indenting, I would instinctively think there was a `link` callback or `if` statement, or something structural.  Of course checking the context would reveal the truth.  And if we decide to keep using redundant code blocks, or expand their use, I would get used to seeing them more.

Next, I tried adding 2 more redundant code blocks to BeersLawScreenView (in addition to the 1 it already has) to see how it looked:

<details>

```js
// Copyright 2013-2020, University of Colorado Boulder

/**
 * Scene graph for the 'Beer's Law' screen.
 *
 * @author Chris Malley (PixelZoom, Inc.)
 */

import ScreenView from '../../../../joist/js/ScreenView.js';
import merge from '../../../../phet-core/js/merge.js';
import ModelViewTransform2 from '../../../../phetcommon/js/view/ModelViewTransform2.js';
import ResetAllButton from '../../../../scenery-phet/js/buttons/ResetAllButton.js';
import Node from '../../../../scenery/js/nodes/Node.js';
import Tandem from '../../../../tandem/js/Tandem.js';
import beersLawLab from '../../beersLawLab.js';
import BLLConstants from '../../common/BLLConstants.js';
import BLLQueryParameters from '../../common/BLLQueryParameters.js';
import BeersLawModel from '../model/BeersLawModel.js';
import ATDetectorNode from './ATDetectorNode.js';
import BeamNode from './BeamNode.js';
import BLLRulerNode from './BLLRulerNode.js';
import CuvetteNode from './CuvetteNode.js';
import LightNode from './LightNode.js';
import SolutionPanel from './SolutionPanel.js';
import WavelengthPanel from './WavelengthPanel.js';

class BeersLawScreenView extends ScreenView {

  /**
   * @param {BeersLawModel} model
   * @param {ModelViewTransform2} modelViewTransform
   * @param {Object} [options]
   */
  constructor( model, modelViewTransform, options ) {

    // assertions
    {
      assert && assert( model instanceof BeersLawModel );
      assert && assert( modelViewTransform instanceof ModelViewTransform2 );
    }

    options = merge( {
      tandem: Tandem.REQUIRED
    }, BLLConstants.SCREEN_VIEW_OPTIONS, options );
    super( options );

    const lightNode = new LightNode( model.light, modelViewTransform, {
      tandem: options.tandem.createTandem( 'lightNode' )
    } );
    const cuvetteNode = new CuvetteNode( model.cuvette, model.solutionProperty, modelViewTransform, BLLQueryParameters.cuvetteSnapInterval, {
      tandem: options.tandem.createTandem( 'cuvetteNode' )
    } );
    const beamNode = new BeamNode( model.beam );
    const detectorNode = new ATDetectorNode( model.detector, model.light, modelViewTransform, {
      tandem: options.tandem.createTandem( 'detectorNode' )
    } );
    const wavelengthPanel = new WavelengthPanel( model.solutionProperty, model.light, {
      tandem: options.tandem.createTandem( 'wavelengthPanel' )
    } );
    const rulerNode = new BLLRulerNode( model.ruler, modelViewTransform, {
      tandem: options.tandem.createTandem( 'rulerNode' )
    } );
    const comboBoxListParent = new Node();
    const solutionPanel = new SolutionPanel( model.solutions, model.solutionProperty, comboBoxListParent, {
      maxWidth: 575,
      tandem: options.tandem.createTandem( 'solutionPanel' )
    } );

    // Reset All button
    const resetAllButton = new ResetAllButton( {
      scale: 1.32,
      listener: () => model.reset(),
      tandem: options.tandem.createTandem( 'resetAllButton' )
    } );

    // Rendering order
    {
      this.addChild( wavelengthPanel );
      this.addChild( resetAllButton );
      this.addChild( solutionPanel );
      this.addChild( detectorNode );
      this.addChild( cuvetteNode );
      this.addChild( beamNode );
      this.addChild( lightNode );
      this.addChild( rulerNode );
      this.addChild( comboBoxListParent ); // last, so that combo box list is on top
    }

    // Layout for things that don't have a position in the model.
    {
      // below the light
      wavelengthPanel.left = lightNode.left;
      wavelengthPanel.top = lightNode.bottom + 20;
      // below cuvette
      solutionPanel.left = cuvetteNode.left;
      solutionPanel.top = cuvetteNode.bottom + 60;
      // bottom right
      resetAllButton.right = this.layoutBounds.right - 30;
      resetAllButton.bottom = this.layoutBounds.bottom - 30;
    }
  }
}

beersLawLab.register( 'BeersLawScreenView', BeersLawScreenView );
export default BeersLawScreenView;
``` 

</details>

The redundant code blocks really don't seem like they are pulling their weight in this example.  They really feel redundant. 
 The code is already organized, and this looks to me like it's adding lines of code without helping.  I would not want to see this pattern promulgated across our codebase.  This is a subjective opinion and I'm here to get feedback from others.

One final thought about the rarity, and another option.  At this rate, we are accruing less than 1 redundant code block per year.  Perhaps when we really want a redundant code block, we could add a disable directive like so:

```js
// Layout for things that don't have a position in the model.
{ // eslint-disable-line no-lone-blocks
  // below the light
  wavelengthPanel.left = lightNode.left;
  wavelengthPanel.top = lightNode.bottom + 20;
  //...
}
```

**Comment by pixelzoom** [comment]
Would you be less confused by if lone blocks were converted to entirely-unnecessary functions, like this example in BeersLawScreenView? 

```diff
Index: js/beerslaw/view/BeersLawScreenView.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/beerslaw/view/BeersLawScreenView.js b/js/beerslaw/view/BeersLawScreenView.js
--- a/js/beerslaw/view/BeersLawScreenView.js	(revision 985bbbd5e8d3bc3077d0705ec6a587da12f4c057)
+++ b/js/beerslaw/view/BeersLawScreenView.js	(date 1618593313907)
@@ -82,17 +82,23 @@
     this.addChild( comboBoxListParent ); // last, so that combo box list is on top
 
     // Layout for things that don't have a position in the model.
-    {
+    const doLayout = () => {
+
       // below the light
       wavelengthPanel.left = lightNode.left;
       wavelengthPanel.top = lightNode.bottom + 20;
+
       // below cuvette
       solutionPanel.left = cuvetteNode.left;
       solutionPanel.top = cuvetteNode.bottom + 60;
+
       // bottom right
       resetAllButton.right = this.layoutBounds.right - 30;
       resetAllButton.bottom = this.layoutBounds.bottom - 30;
-    }
+    };
+    doLayout();
   }
 }
 ```

**Comment by samreid** [comment]
That suffers from the same problem.

**Comment by pixelzoom** [comment]
The "same probem" being what?  It doesn't fail no-lone-blocks.

**Comment by pixelzoom** [comment]
Here's another good example, used throughout graphing lines.  This makes it very obvious that there's a block of things that need to be done while the guard flag is `true`. 

```js
      // Synchronize the controls atomically.
      updatingControls = true;
      {
        // ... all of the things that need to be done while updatingControls is true.
      }
      updatingControls = false;
```

> Perhaps when we really want a redundant code block, we could add a disable directive like so:

I've made my opinion known.  And I've added eslint-disable comments to the sim-specific code that I'm responsible for.   I'm bowing out of this discussion and will leave it to the team to decide what to do with the remaining lone blocks.  While I'm the primary author for FaucetNode.js, feel free to do whatever you want.  The other lone blocks are in code written by @jonathanolson and @veillette.

**Comment by samreid** [comment]
> The "same probem" being what?

From https://github.com/phetsims/chipper/issues/1026#issuecomment-820883959 I said:

> these are so rare, if I saw additional indenting, I would instinctively think there was a `link` callback or `if` statement,

It doesn't matter whether the indenting is from an IIFE or a temporary function or a lone block--since these strategies are much less conventional in our project, I have been trained to see that next level of indenting as part of a control block or link callback, etc.  I'm sure I could find numerous counterexamples to this, and it is not a huge problem, but I wanted to make sure the point is understood.

**Comment by pixelzoom** [comment]
>  I have been trained to see that next level of indenting as part of a control block or link callback, etc. . I'm sure I could find numerous counterexamples to this, and it is not a huge problem, but I wanted to make sure the point is understood.

I fully understand that you have an incorrect understanding of blocks and block syntax.  I wouldn't call that "training", I'd call that "anti-training".   What I don't understand is why other developers shouldn't use something because you don't recognize it.  

I'll also point out that in this entire discussion, you have not identified a single lone block that is actually problematic and does not meet the criteria for non-control block usage.

**Comment by samreid** [comment]
> That of course will fail the "no-lone-blocks" rule.

I recommend testing that hypothesis--the results may surprise you.

> you have an incorrect understanding of blocks and block syntax.

I use indentation as a context cue to understand what's happening in the code.  At the risk of being overdramatic, here are some heuristics:

No indentation: entry-point code, nothing interesting happening contextually
One Level: perhaps a class declaration or top level function
Two Levels: within a class, this probably means we are in a constructor or method
Three Levels: something else is happening...
5 or more levels: something complicated may be happening...

> I'll also point out that in this entire discussion, you have not identified a single lone block that is actually problematic and does not meet the criteria for non-control block usage.

In my comment https://github.com/phetsims/chipper/issues/1026#issuecomment-820883959 I went so far as to add even more lone blocks to see how great they were. Upon reflection, I wrote:

> The redundant code blocks really don't seem like they are pulling their weight in this example. They really feel redundant.  The code is already organized, and this looks to me like it's adding lines of code without helping. I would not want to see this pattern promulgated across our codebase. This is a subjective opinion and I'm here to get feedback from others.

I was not referring to just the new the code blocks I added, but the pre-existing one as well.

> What I don't understand is why other developers shouldn't use something because you don't recognize it.

Why should this issue hinge on how I perceive indentation?  Before I mentioned that, another team member said:
> I recommend we adopt [the no-lone-blocks rule]. generally seems like it wouldn't pass code review.

And the **consensus** at the prior dev meeting was:
> Many of the cases we looked at we thought were unnecessary [...]

Redundant lone blocks are unconventional for our project. I'm recommending to capture that heuristic in a lint rule. A new developer or intern that misuses them will get immediate feedback about our convention. If your argument is "they are great, we should use them much more frequently", then I disagree with that for the reasons mentioned above.

**Comment by pixelzoom** [comment]
> And the **consensus** at the prior dev meeting was:
> 
> Many of the cases we looked at we thought were unnecessary [...]

There is no such statement in the prior dev meeting notes at https://github.com/phetsims/chipper/issues/1026#issuecomment-820677930.  Those who expressed an opinion said the exact opposite:
> @jonathanolson, @jbphet and @pixelzoom agreed we should allow blocks and not add the lint rule.

We were ready to close this, and left it open at @samreid's request, for more discusion.

**Comment by pixelzoom** [comment]
> I use indentation as a context cue to understand what's happening in the code. At the risk of being overdramatic, here are some heuristics:

Your heuristics do not account for the fact that block !== control block.


>>    I'll also point out that in this entire discussion, you have not identified a single lone block that is actually problematic and does not meet the criteria for non-control block usage.
>
> In my comment #1026 (comment) I went so far as to add even more lone blocks to see how great they were. Upon reflection, I wrote:
>
> > The redundant code blocks really don't seem like they are pulling their weight in this example. They really feel redundant. The code is already organized, and this looks to me like it's adding lines of code without helping. I would not want to see this pattern promulgated across our codebase. This is a subjective opinion and I'm here to get feedback from others.

You are repeatedly trying to make a "redundancy" case, which is subjetive, and based on your feeling that we shouldn't use lone blocks because they don't match your understanding of (and heuristics for) blocks.

So one more time...  Please point out a block that violates this definitiion in any objective way -- e.g. not logically related statements, poor doc, etc.  
> "The function of blocks in programming is to enable groups of statements to be treated as if they were one statement, and to narrow the lexical scope of objects such as variables, procedures and functions declared in a block so that they do not conflict with those having the same name used elsewhere."

**Comment by pixelzoom** [comment]
> > That of course will fail the "no-lone-blocks" rule.
> I recommend testing that hypothesis--the results may surprise you.

It wasn't a hypothesis, I encountered it in the referenced example. But I must've been doing something else wrong.  In any case (no pun intended :) there are 3 lone blocks used of case statements in SingularValueDecomposition.js, and I see zero value in removing them.

**Comment by samreid** [comment]
I discussed this with @pixelzoom over slack, and we agreed that `ChallengeFactory1.js` is a good use of redundant lone blocks.  Since our production code has a legitimately good use for this language feature, I would like to change my vote to disable the rule.  It seems unlikely that someone would overuse or misuse this feature--if that happens in the future, we can revisit.  But for cases like:

```js
    // check all the assertions
    {
      assert && assert( model instanceof BeersLawModel );
      assert && assert( modelViewTransform instanceof ModelViewTransform2 );
    }
```

@pixelzoom and I agreed we probably wouldn't use a lone block in that case.

**Comment by pixelzoom** [comment]
4/22/21 dev meeting vote:

6 to delete rule, 0 to keep rule, 2 to abstain

@samreid will delete the rule.

**Comment by samreid** [comment]
I commented that we plan to leave the rule off, and I removed the corresponding disable directives, closing.
