### ISSUE TITLE
Rename locale "Kurdish (Turkey)" to "Kurdish (Kurmanji)"

### ISSUE THREAD

**Issue by mattpen** [phetsims/chipper#1111]
Related to phetsims/website#1270

Kurdish (Turkey) doesn't accurately represent the language being used by the locale code ku_TR and we should be using Kurdish (Kurmanji) instead. @oliver-phet proposed that we simply change the display name for that locale, but I'm not sure what the ramifications of that are, if any. On the website side, there could be conflicts with legacy Java Locale support. Alternatively, we could create a new locale with a [User-assigned ISO-3166 code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#User-assigned_code_elements) and give it the display name Kurdish (Kurmanji), for example ku_QU or ku_XU.

This would affect the localeInfo.js and localeInfo.json files in chipper which are used by various phet systems (rosetta, yotta, etc).

**Comment by chrisklus** [comment]
From 11/4/21 dev meeting:

CM JB: Prefer coming up with a custom locale code instead of changing an existing one
JO: I should be involved to handle the stats side of things
ON: we created ku_TR to represent Kurdish (Kurmanji), but there is a standard 3 letter code for Kurdish (Kurmanji)

JO: What is our precendent for coming up with new locale codes and giving them the appropriate labels?
MP: Yes, we've done this a few times.

Consensus: We will create a locale code for Kurdish (Kurmanji) and use the existing translations for ku_TR for that code. We can't currently support the standard 3 letter code for Kurdish (Kurmanji) so will come up with our own custom one in the xx_XX style. Assigning to subgroups to proceed.

**Comment by jbphet** [comment]
@mattpen - I'm starting to investigate ways to address this, and I have a few questions:

- When you say, "Kurdish (Turkey) doesn't accurately represent the language being used by the locale code ku_TR and we should be using Kurdish (Kurmanji) instead", what is the source for this?  Was there an email request from a translator?
- Our translation process doesn't enforce any particular character set or linguistic choices for a given locale, so does this mean that a previous translator used the locale code incorrectly?
- Where did the QU and XU suffixes come from?  I looked at the information about user-assigned codes that you linked above, and it said "The code XU is being used by WIPO as an indicator for the International Union for the Protection of New Varieties of Plants", so I wasn't sure how it related.  I didn't see anything there about QU.

**Comment by jbphet** [comment]
For reference, there are currently 3 translations using the `ku` locale and 2 using the `ku_TR` locale.

**Comment by oliver-phet** [comment]
> @mattpen - I'm starting to investigate ways to address this, and I have a few questions:
> 
> * When you say, "Kurdish (Turkey) doesn't accurately represent the language being used by the locale code ku_TR and we should be using Kurdish (Kurmanji) instead", what is the source for this?  Was there an email request from a translator?

There was a request back in 2014 to support Kurmanji. It was decided then to use ku_TR even though Kurmanji isn't specific to Turkey. Related [unfuddle ticket](https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3630). We had another translator recently that highlighted that we shouldn't be using "Kurdish (Turkey)" to describe "Kurdish (Kurmanji)" (and I agree). @mattpen laid this out above but I would like to either (1) change the display name for that locale or (2) create a custom locale using a user-assigned code.
> * Our translation process doesn't enforce any particular character set or linguistic choices for a given locale, so does this mean that a previous translator used the locale code incorrectly?

See above. We provided the code ku_TR to the translator as a way to support Kurmanji.

> * Where did the QU and XU suffixes come from?  I looked at the information about user-assigned codes that you linked above, and it said "The code XU is being used by WIPO as an indicator for the International Union for the Protection of New Varieties of Plants", so I wasn't sure how it related.  I didn't see anything there about QU.

[See the link](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#User-assigned_code_elements) provided by @mattpen

> The following alpha-2 codes can be user-assigned: AA, QM to QZ, XA to XZ, and ZZ.

**Comment by jbphet** [comment]
@oliver-phet and @RVieyra - This issue was discussed with @kathy-phet at today's development planning meeting, and @kathy-phet recommended that we assign it to you to do a bit of investigation and make sure that people would really take advantage of these changes if we make them.  Currently, there are only two sim translations for the `ku_TR` locale, and we have done work in the past for custom locales that saw little or now use, so we'd like to get some indication as to whether this is really worth the time and effort.

Once vetted, please assign back to me.

**Comment by oliver-phet** [comment]
I just sent a follow up email to the user/company requesting this locale.

**Comment by oliver-phet** [comment]
@jbphet It sounds like we should forego adding this custom locale code. 

> We don't know if we will be able to do more translations in Kurmanji this year, so we suggest we include our translation of the Circuit Construction Kit to the already existing page Kurdish (Turkey), since all translations there are also Kurmanji. We don't want to cause you any trouble! 
> If it was possible, maybe it would be useful to add the word kurmanji somewhere in the page, to make sure that users searching for sims in kurmanji will be able to find it. 

I'm going to close this issue for now and continue the discussion of possible changing/adding "Kurmanji" in https://github.com/phetsims/website/issues/1270.
