### ISSUE TITLE
new grunt task for creating thumbnail and screenshot images

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/chipper#113]
I am thinking of adding a new grunt task to chipper's Gruntfile. My plan is to call it image-resize.

It relies on a grunt plugin called grunt-image-resize (https://github.com/excellenteasy/grunt-image-resize) and having imagemagick installed on your computer. I think it would require changing all of the package.json files to include:

```
    "grunt-image-resize": "^1.0.0",
```

Running grunt image-resize would create two downscaled versions of the screenshot image in assets and put them in the build directory, a -128.png and -600.png for the thumbnail and the screenshot. That way, they'd be ready to go when copying to figaro.

Any objections or input on this?

**Comment by jonathanolson** [comment]
I've worked to make it so native dependencies aren't required so far in the build, since it makes the process to get started much more complicated. Instead of just saying:

node.js, git and then install grunt-cli (using npm)

it would be:

node.js, git, grunt-cli, decide between (and install) MinGW / Cygwin (which is a much more complicated process on windows), set up the package and get executable paths right (and execute node.js from within that environment), or choice between macports / homebrew on Mac, etc.

in order to build sims. That's one of the critical reasons why I selected pngjs and jpeg-js for doing the mipmapping, although at least imagemagick has binaries available for all platforms.

For instance, https://www.npmjs.com/package/lwip looks like it supports lanczos, which is probably what we'd want, and wouldn't require a complicated process to have everyone install.

**Comment by samreid** [comment]
I agree with @jonathanolson

**Comment by pixelzoom** [comment]
+1

**Comment by aaronsamuel137** [comment]
Sounds good. I agree that having an external dependency is a bad idea. I can go ahead and implement with lwip if that seems like a good idea to everyone. Let's discuss details during the next dev meeting.

**Comment by jonathanolson** [comment]
Sounds good to discuss. Also I saw lwip after just a few seconds of Googling, I'm not saying it's the specific one we should use (but looks like something promising).

**Comment by aaronsamuel137** [comment]
I looked into implementing this with the jimp module. It seems to work as expected half of the time, but the other half it just creates an empty image file. I haven't found any explainable reason why this might be, so I have made an issue in the jimp repo. I'll put this on hold for a bit until I hear back.

**Comment by pixelzoom** [comment]
@aaronsamuel137's work is currently in the "jimp" branch of chipper.

**Comment by aaronsamuel137** [comment]
Jimp branch has been merged to master. The task: ```grunt generate-thumbnails``` will generate two thumbnails: [project name]-128.png (128x84) and [project-name]-600.png (600x394).

There is bug with Jimp that sometimes causes an empty image to be written. @samreid and I looked at this and determined that the bug has been fixed in current master, but has not yet been published to npm. There is an issue open in Jimp to republish: https://github.com/oliver-moran/jimp/issues/16

For now, I'd say feel free to use this if you want, just double check and make sure it works. (It worked for @samreid 100% of the time so far, so it will most likely work).

**Comment by pixelzoom** [comment]
@aaronsamuel137 In generateThumbNails, you're disabling a jshint warning:

```js
  /* jshint -W031 */
  new Jimp( fullResImageName, function() {
    this.resize( width, height ).write( destinationFile, done );
  } );
```

Could you please (1) indicate why the warning is being disabled, and (2) turn it back on at the end of the relevant code (otherwise it stays off any may mask legitimate problems.)

Also please add @author to generateThumbNails.js.

**Comment by pixelzoom** [comment]
I moved registration of the 3 thumbnail tasks to the "Utility" section, which is things that you run manually when you need them,  Things in "Primary" section are part of the primary 'build' task.

**Comment by aaronsamuel137** [comment]
I've made these updates. Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
Whoops, not sure I should have closed this issue. The changes that @aaronsamuel137 asked me to review look great.  But I'm not sure it there's other work to be done.  @aaronsamuel137 if you're done, feel free to close this.

**Comment by pixelzoom** [comment]
@aaronsamuel137 you merged the 'jimp' branch into master.  Is there any reason to keep the 'jimp' branch, or can it be deleted?

**Comment by aaronsamuel137** [comment]
No reason to keep it. I just deleted it.

**Comment by pixelzoom** [comment]
@aaronsamuel137 If you haven't done so already, highly recommend to announce the new dependency to the Google Group, instructions to `npm install`, etc. I got bitten by it, so has the student team working on quantum-bound-states.  I'm guessing one of the 3rd-party developers will hit it too.

**Comment by aaronsamuel137** [comment]
Good point, thanks for the reminder. I have posted to the google group.

**Comment by pixelzoom** [comment]
@aaronsamuel137 is there anything else to do for this issue?

**Comment by aaronsamuel137** [comment]
This is basically done. We'll just need to update the version number for jimp in package.json once the new version of Jimp is deployed. See: https://github.com/oliver-moran/jimp/issues/16#issuecomment-97595029.

**Comment by aaronsamuel137** [comment]
Jimp has been updated, closing.
