### ISSUE TITLE
How to provide type information for nested string keys?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1139]
Type information for nest keys (like `"screen.blah"`) is not currently available in the *Strings.js file.

For example, these will be flagged as TypeScript errors:

```js
// geometric-optics-main.js
  const sim = new Sim( geometricOpticsStrings[ 'geometric-optics' ].title, [

// geometric-optics.IntroScreen.js
name: geometricOpticsStrings.screen.intro,
```

There are at least 3 variation of a workaround that have been implemented, all using a d.ts file.

(1)  @samreid @jonathanolson and I can up with this workaround, adding 
geometric-optios/js/geometricOpticsStrings.d.ts:

```ts
type t = {
  [ key: string ]: string,
  'geometric-optics': {
    title: string,
  },
  screen: {
    [ key: string ]: string,
  }
  //TODO add any other nested strings here
};
let geometricOpticsStrings: t;
export default geometricOpticsStrings;
```

(2) Gravity and Orbits has this for gravityAndOrbitsStrings.d.ts:

```js
type t = { [ key: string ]: string };
let gravityAndOrbitsStrings: t;
export default gravityAndOrbitsStrings;
```

That doesn't address the sim's title, and requires a `@ts-ignore`:

```
// @ts-ignore
const gravityAndOrbitsTitleString = gravityAndOrbitsStrings[ 'gravity-and-orbits' ].title;
```

... and it doesn't address "screen" - because it doesn't use that convention for screen string keys!

(3) Greenhouse has yet-another variation in greenhouseEffectStrings.d.ts:

```ts
let greenhouseEffectStrings: any;
export default greenhouseEffectString
```

Two questions:

(1) What is the preferred pattern until we have a longterm solution? This seems important so that we don't end up with a bunch of different ways of doing the same thing, and so that other developers don't encounter the same confusion that I had while looking for exemplars.

(2) What is the longterm solution?

**Comment by samreid** [comment]
I added a new step to `grunt modulify` (which runs automatically with `grunt update`) that generates type information for nested string keys.  I used it to regenerate all of the string files for TypeScript sims.  This identified a few potential type mismatches which I'll mention or address in commits shortly.

The main constraint of this new feature is that after editing the strings.json file in a TypeScript sim, you must run `grunt modulify`.  I'll send a Public Service Announcement on the typescript channel.

This feels like a reasonable medium-term solution to me, but I think we could get rid of this `grunt modulify` step altogether if we change the storage medium from JSON to TS.  This would probably change the structure of the tree, and would require updates in rosetta, so that would require coordination and discussion if we want to go there.  But I have to say I'm not too worried about the `grunt modulify` step since it is working well for images/sounds and strings are just another form of non-source code to be dealt with in modulify.

**Comment by samreid** [comment]
I sent this public service announcement on slack typescript:

> For https://github.com/phetsims/chipper/issues/1139 we standardized on how to deal with translated strings in TypeScript.  This requires a new grunt modulify step after adding/removing strings in the JSON file. (Some prefer to run modulify as part of grunt update).  I’ve removed the various other workarounds that were in place.

@pixelzoom would you like to review?

**Comment by pixelzoom** [comment]
Looks OK in geometric-optics.   Closing.

**Comment by pixelzoom** [comment]
Reopening, based on a Slack discussion.

The type in all *Strings.js files is called `StringsType`.  I realize that this type is private to the file. But would something like `KeysType` be better? (more accurate, less potentially confusing) These are the values of the keys (field names), not the string values.

**Comment by pixelzoom** [comment]
Nevermind. I get it now. StringsType is the shape of the object literal returned by *Strings.js. So that type name is appropriate.
