### ISSUE TITLE
How should we deal with TypeScript type information for IOType.fromStateObject and IOType.applyState?

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1141]
In the developer meeting notes, @jbphet said:

> I feel like I’m glossing over a lot of stuff when I do TS conversion on phet-io things.  I was looking for good examples, and it seems like the same things were done in GAO.  For example, look at BodyIO in Body.ts.  The stateSchema and the in-line type definition in applyState seem redundant, and require devs to know that a NumberIO is a number, and uses the “any” type for the more complex IO type.  There is no return type specified for toStateObject.  Yet there are no TODOs or anything here.  Is this what I should do too, and we would just count on searching for “any” once more of the phet-io-typescript relationship is worked out?  I feel like we will end up with a lot of partially converted code.  Is there an issue in GitHub somewhere for addressing this?

**Comment by samreid** [comment]
Here is the BodyIO code @jbphet mentioned:

```ts
const BodyIO = new IOType( 'BodyIO', {
  valueType: Body,
  documentation: 'Represents a physical body in the simulation',
  toStateObject: ( body: Body ) => body.toStateObject(),
  applyState: ( body: Body, stateObject: { pathLength: number; modelPathLength: number; path: any; } ) => body.setStateObject( stateObject ),
  stateSchema: {
    pathLength: NumberIO,
    modelPathLength: NumberIO,
    path: ArrayIO( Vector2.Vector2IO )
  }
} );
```

It seems better to mark the whole stateObject as `any` for now, I'll do that in an upcoming commit.

**Comment by samreid** [comment]
We get the `stateObject` from a serialization step, so I'm not sure how to add types to it.  What would be ideal is to say that "the parameter type of `setStateObject` is the same as the inferred return type of `toStateObject`", but I'm not sure if/how this can be accomplished.

**Comment by samreid** [comment]
Following, https://stackoverflow.com/questions/36015691/obtaining-the-return-type-of-a-function I matched the state object types.  The pattern looks like this:

```js
  /**
   * @public (phet-io)
   */
  toStateObject() {
    return {
      pathLength: this.pathLength,
      modelPathLength: this.modelPathLength,
      path: ArrayIO( Vector2.Vector2IO ).toStateObject( this.path )
    };
  }

  /**
   * @public (phet-io)
   */
  setStateObject( stateObject: ReturnType<typeof Body.prototype.toStateObject> ) {
    this.pathLength = stateObject.pathLength;
    this.modelPathLength = stateObject.modelPathLength;
    this.path = ArrayIO( Vector2.Vector2IO ).fromStateObject( stateObject.path );
    this.clearedEmitter.emit( this.type );
    this.path.forEach( pathPoint => this.pointAddedEmitter.emit( pathPoint, this.type ) );
  }
```

That is, the return type of `toStateObject` is inferred by the compiler, and we constrain the parameter type of `setStateObject` to match the return type of `toStateObject`.

This should be reviewed and discussed before we apply it everywhere.

**Comment by jbphet** [comment]
This is assigned to me and marked as ready-for-review, so here are my comments and questions:

- If the `ReturnType<typeof Body.prototype.toStateObject>` thing really works, that seems like a good way to specify the type and avoid having to duplicate it
- Why is the method called `setStateObject` instead of `applyState`?  I thought `applyState` was the convention, and I just searched through the codebase, I only see this instance of `setStateObject`, so I'm wondering whether it's a mistake or a proposal for a new convention.
- The state schema is still being specified later in this file, and it is essentially the same information as the inferred type.  This seems redundant.  Can it be eliminated?  If this is something that other devs feel should be addressed separately, feel free to say so, but I am of the mind that should have all elements of the pattern for TypeScript worked out before we, as @samreid says above, "apply it everywhere".
- Sometimes instead of `applyState` we use `fromStateObject` for situations where it's better to create a new object than to set the state of an existing one.  It's probably pretty straightforward to apply the same approach as is described above, but it would be good to have an example in this issue regardless so that it's clear what is being proposed.
- There are some emitters being fired at the end of the `setStateObject` method shown above.  I'm assuming that these lines of code are unique to `Body.ts` and not part of the general pattern.  True?

**Comment by zepumph** [comment]
This is going to need quite a bit more design consideration. @kathy-phet @markgammon and I were going through my "ready-for-review" labelled items today, and we felt like this doesn't warrant that label. I feel like https://github.com/phetsims/gravity-and-orbits/commit/2783a0f5fe7f5e7c5c41d7785abfd2f732ab8185 was enough of a bandaid to continue, and that we will likely want to come up with a more general solution soon, like one the works for StateSchema (likely meaning we convert that class too).

**Comment by samreid** [comment]
We introduced StateType type parameter in https://github.com/phetsims/chipper/issues/1253, closing.
