### ISSUE TITLE
WebStorm: Auto-imports from a *.js file into a *.js file don't work any more

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1166]
@pixelzoom pointed out that auto-imports from a *.js file into a *.js file don't work any more.  @jessegreenberg and I confirmed the same behavior.  When did this break?  Is it related to TS or tsconfig?  Can it be repaired?  Can we set up a self-contained reproducible example without using the phet codebase?  Should it be reported to JetBrains?

**Comment by pixelzoom** [comment]
Also worth noting:
* WebStorm 2021.3 was release 11/27/2021.
* I'm using WebStorm 2021.3, while @jessegreenberg is using 2021.2.2. We're both seeing the problem, so it's not a new breaking change in WebStorm
* I haven't worked on .js files since I converted Geometric Optics to TS (that started ~11/1/2021).  I'm certain that .js imports were working fine in 2021.2.2 prior to that.

**Comment by jbphet** [comment]
I just tested auto-imports into JS files in IntelliJ IDEA 2021.3 (Ultimate Edition), and it is broken there too.  I tested it in the _Build an Atom_ sim, which has had no TypeScript work done on it to date.  @samreid - Unless you think this problem is somehow related to changes made to our code base to support TypeScript, I think it would be worthwhile to report it to JetBrains.  If I remember correctly, you were already working with them on fixing some issues with imports for TypeScript, so this seems like it could be part of the follow-up on that effort.

**Comment by samreid** [comment]
Some tests that may help determine if TypeScript is related to this problem:

* Create a clean JS repo from scratch and see if there are problems
* Disable the TypeScript plugin and see if there are problems

**Comment by pixelzoom** [comment]
This is apparently still affecting everyone who is working in .js files.  It sure is making my life difficult.  And @zepumph said in Slack:


> Michael Kauzmann:octopus:  3:45 PM
> Same for me! I am hitting this really consistently these days.
>
> ![image](https://user-images.githubusercontent.com/3046552/145901292-302be5f3-706c-4f0f-a5cf-f31715e608d4.png)

**Comment by zepumph** [comment]
This is not the same issue at all, but it related enough that I thought I'd tag https://github.com/phetsims/chipper/issues/1126, in which @jbphet and I were finding that in typescript files, depending on the way we were trying to import a file, the typescript engine in webstorm was not finding the file to import (Ctrl+Space vs Alt+Enter mattered)

**Comment by samreid** [comment]
I created a blank WebStorm project, and added 2 *.js files, and saw that imports worked really well. It imported on autocomplete and on alt+enter.

**Comment by samreid** [comment]
From today's meeting, we agree this is a problem.  @samreid will test a blank project with a "far away" structure, and report it to JetBrains at high priority.

**Comment by samreid** [comment]
I was hopeful about WebStorm 2021.3.1 since it had a lot of release notes about fixing imports, https://confluence.jetbrains.com/display/WI/WebStorm+213.6461.19+Release+Notes but it's still buggy.

**Comment by samreid** [comment]
Things are working fine in an empty project:

![image](https://user-images.githubusercontent.com/679486/146490288-2d017f3d-5682-4c44-8b4e-4821ab80cae2.png)

So there must be something different about our projects.

**Comment by samreid** [comment]
I isolated the problem and submitted a bug report to JetBrains here: https://youtrack.jetbrains.com/issue/WEB-54083

**Comment by samreid** [comment]
JetBrains replied in https://youtrack.jetbrains.com/issue/WEB-54083#focus=Comments-27-5665822.0-0

**Comment by jessegreenberg** [comment]
Over slack @mattpen said that dependencies can be installed from github with npm and package.json. I wonder if WebStorm can use this info to better support auto imports. https://www.pluralsight.com/guides/install-npm-packages-from-gitgithub

If not from github, you can specify local dependencies in package.json like this https://stackoverflow.com/questions/15806241/how-to-specify-local-modules-as-npm-package-dependencies, maybe that will help WebStorm.

**Comment by samreid** [comment]
I added a script that would likely help here: https://github.com/phetsims/chipper/issues/1320

**Comment by samreid** [comment]
Still broken in 2023.1

**Comment by zepumph** [comment]
Will you explain that to me? I have found it to be fixed, but in order to get the import, you have to have imported that library (or maybe file) from that repo before. Was it perhaps the first `scenery-phet` import from the repo or something? 

Importing a JS file from a js file:

![image](https://user-images.githubusercontent.com/6856943/231598318-e7b4f1c7-6824-4c00-8c9c-cd231b8fc2e2.png)


Importing a TS file from a js file:

![image](https://user-images.githubusercontent.com/6856943/231598349-44d28b86-1263-47ed-82b1-afa9348a0693.png)

**Comment by samreid** [comment]
Right, I was testing importing from a repo that did not yet have any imports.

**Comment by zepumph** [comment]
Over in https://youtrack.jetbrains.com/issue/WEB-54083#focus=Comments-27-5665822.0-0 the jetbrains representative said:

>The only downside of the approuch is that you still have to write the first import manually to create the dependency between the packages.

So you will still need to create a single link between two "packages" (repos) before getting the behavior I had. That is much nicer than per-file which is what I kinda thought up in https://github.com/phetsims/chipper/issues/1166#issuecomment-1506037819

What else would you like to do for this issue?

**Comment by samreid** [comment]
Thanks, I was unaware of that comment. I recommend closing this issue. Anyone please reopen if you wish.
