### ISSUE TITLE
Where should design pattern documentation for Typescript go?

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1181]
From quarterly goal conversation:

CM: We need to keep the javascript patterns around since they will stick in our codebase.
KP: Seems like they should be in a separate file.

During the conversation it was noted that options, enumerations, and mixins were the main patterns that need updating documentation.

I personally feel like we should add this into the existing sections in that document, since it is only a subset of sections that will differ between language.

**Comment by zepumph** [comment]
In https://github.com/phetsims/chipper/issues/1106#issuecomment-1042417382 @pixelzoom was surprised to see me adding new typescript patterns to our existing design-pattern documentation. 

From above:

>I personally feel like we should add this into the existing sections in that document, since it is only a subset of sections that will differ between language.

I still feel this way. To my knowledge, we will be updating enumeration and options pattern. I see the `phet-design-patterns` document as a holistic spot to see the patterns used in our project. If things differ between typescript and javscript, it should be noted there.

**Comment by jessegreenberg** [comment]
This was discussed in dev meeting 2/17/21:

Consensus was to keep old JavaScript patterns in the pattern documentation. Even patterns that no longer exist in code on master should remain so that we have documentation of them for new developers, third party developers, and when we need to maintain old code.  We will add a note to the pattern documentation describing that old patterns may exist, and to use the new ones when possible.

We did a poll in the meeting notes:

<details>

Vote: Should the design patterns document have old patterns that exist in the project but are no longer the recommended way of doing things.
MK - A small shout out feels great. If it is no longer used at all in the project (like our `mixInto()` mixin strategy), then I don’t think it should stick around.
SR - A mention and callout in the document seems appropriate, especially for something widespread across our codebase like deprecated Enumerations
SR: Historical patterns that no longer exist in our codebase should be deleted.  3rd parties can access that documentation through a historical sha.
MG
CM
JG - We should have documentation for both old and new styles. Whether they are in the same or different docs, I don’t feel strongly. I doubt we will fully replace JavaScript in the project.
Older patterns that have been fully removed should still remain for third parties and maintenance.
CK - documentation for deprecated patterns somewhere seems nice, but no preference on where. Nope ?
JO - out
JB - A “Deprecated Patterns that Might Exist in Older Code” section seems like it would be helpful, especially to new team members and outside developers.  Older patterns that might exist on release branches should be left and not actively removed, though it would not be worth our time to document old, previously undocumented patterns.
MP- out

</details>
