### ISSUE TITLE
Improve tooling for Typescript

### ISSUE THREAD

**Issue by markgammon** [phetsims/chipper#1182]
Devs: SR(40), MK(5)

### Q1 Priority
1. Eliminating time for commit and pre-commit via pre-commit script
https://github.com/phetsims/chipper/issues/1174

2. Eliminate friction between tools running 
https://github.com/phetsims/chipper/issues/1173

3. Creating JetBrains issues for feedback/requests

Other cases/issues:
https://github.com/phetsims/chipper/issues/1167
https://github.com/phetsims/chipper/issues/1163
https://github.com/phetsims/chipper/issues/1140

### Q2 Priority
1. Stack traces on CT - improvement there. On a branch but not complete. Close to being done.  https://github.com/phetsims/chipper/issues/1140
(ON HOLD UNTIL JB INVESTIGATION) 2. Time for the pre-commit with githooks (on windows) - JG is 1 min worst case. MK is 4 min. JB is 3 min. (CM thinks maybe if running ??? then stuff is cached).

**Comment by samreid** [comment]
Our TypeScript tooling improved significantly this quarter.  All issues mentioned above are closed aside from https://github.com/phetsims/chipper/issues/1167 which I increased priority and will look at separately.

Additionally, we improved the structure of our TypeScript configuration in https://github.com/phetsims/chipper/issues/1245 and made significant improvements using typescript lint.  I think this issue is ready to close.
