### ISSUE TITLE
`no-empty-function` typescript-eslint rule

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1249]
Related to https://github.com/phetsims/chipper/issues/1114.
Documentation at https://typescript-eslint.io/rules/no-empty-function/.
To be discussed in dev meeting.

**Comment by jessegreenberg** [comment]
Consensus 5/26/22 - We want this rule. Better to use `_.noop` instead because it is easier to read and more consistent.

JO: Can we have the lint rule recommend `_.noop` instead?
MK: The best we can do is add documentation where we enable the rule.

SR and MS will work on enabling this lint rule, thanks!

To enable we will want to disable the javascript rule like this:

```json
{
  // note you must disable the base rule as it can report incorrect errors
  "no-empty-function": "off",
  "@typescript-eslint/no-empty-function": ["error"]
}
```

There are only 41 errors currently.

**Comment by samreid** [comment]
> Better to use _.noop instead because it is easier to read and more consistent.

When @marlitas and I investigated, we found that `_.noop` is not a good replacement for these cases because it has this type signature:

```ts
    interface LoDashStatic {
        /**
         * A no-operation function that returns undefined regardless of the arguments it receives.
         *
         * @return undefined
         */
        noop(...args: any[]): void;
    }
```

That means this code fails the type checker, as it should:

```ts
const x = () => {};
x( 1, 2, 3 );
```

However, using `_.noop` would no longer fail the type checker, which is bad:

```ts
const x = _.noop;
x( 1, 2, 3 ); // No type error!
```

Therefore, we don't want to use `_.noop` everywhere.

Instead, we discussed adding a 0-arg noop in PHET_CORE like `noop0 = ()=>{}`, but that would change occurrences from:

```ts
      // Override the parent implementation as a no-op.  DerivedProperty values appear in the state, but should not be set
      // back into a running simulation. See https://github.com/phetsims/phet-io/issues/1292
      applyState: () => { },
```

to

```ts
      // Override the parent implementation as a no-op.  DerivedProperty values appear in the state, but should not be set
      // back into a running simulation. See https://github.com/phetsims/phet-io/issues/1292
      applyState: noop0,
```

This was not a clear advantage, so we decided to cease work on this issue and return to dev meeting.

We also noticed there are options for the rule, so we could turn on this rule for, say, methods but not arrows.  But let's check in the dev meeting before proceeding.

**Comment by samreid** [comment]
At today's meeting, the team agreed that type checking on the no-op args is not important, so we can proceed with _.noop.

**Comment by marlitas** [comment]
@samreid and I enabled the no-empty-function rule, and used _.noop or line comments as needed. Closing.

**Comment by pixelzoom** [comment]
In the above commits, I removed the `no-empty-function` rule wherever it had been added in package.json.
