### ISSUE TITLE
How should we access private methods for unit tests?

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1295]
In https://github.com/phetsims/axon/issues/403, @zepumph said:

> That said I have no nice ideas about how to keep this item on the class private when using it in tests, but I run into this all the time and I hate marking these fields as public.

and 

> I would almost prefer hacking the types in tests, likely with ts-ignore statements, but that is likely not a universal preference across the team.

However, @marlitas reported another solution to this problem which is described in https://stackoverflow.com/questions/35987055/how-to-write-unit-testing-for-angular-typescript-for-private-methods-with-jasm and https://github.com/microsoft/TypeScript/issues/19335

We tested this in Mean: Share and Balance and it seemed reasonable (commit coming up), so we wanted to share it with the dev team.

**Comment by jessegreenberg** [comment]
@marlitas shows using square bracket notation to access private fields and methods in unit tests. `distributeWater` is a private method.
```ts
introModel[ 'distributeWater' ]( connectedCups, connectedCups[ index ], waterDelta );
```

This is better than a `@ts-ignore` because the ignore could mask other problems. And this is better than changing the API just for testing.

We like it! And will continue to use it in testing files.

@marlitas and @samreid mentioned a lint rule to disallow this in TS implementation files. @zepumph cautioned that this syntax does have some legitimate uses in sim code though. @samreid proposed https://eslint.org/docs/latest/rules/dot-notation. It may not cover all our cases, but is worth investigating.
MS: I think that bracket notation is common enough that it shouldn't be disallowed with lint rule.
JG: +1
MK: There are 183 failures of dot-notation (ignoring the title access in main files). I think investigating this lint rule makes sense.
MK: We already have an item in our code review checklist that says bracket notation is not allowed.

KP: Where should this go in documentation?

Consensus: Next steps are to investigate `dot-notation` rule and then our own custom one if that does not work out.

**Comment by zepumph** [comment]
Ok. I was able to successfully add this dot-notation lint rule for typescript and javascript. I also added overrides so that we are ignoring it it *Tests and *tests files. I then went through ts-ignores in test files and updated private member access to use bracket notation. @marlitas will you please give a review/spot check?

**Comment by zepumph** [comment]
I noticed that dot-notation was already turned on for javascript, I just added it for typescript and the overrides to remove it for test files.

**Comment by marlitas** [comment]
@zepumph looks good. 

I didn't see any changes for updating the member access in the corresponding class, not sure if any previously using dot notation needed to be updated to `private` from `public` at their declaration. 

If not, all looks good to me. Back to @zepumph

**Comment by zepumph** [comment]
Ahh of course, ya know, the whole reason we did this work! I searched for many things like:

"(tests)"
"for tests"
/public.*tests/

and some others. Can you find any more?

**Comment by marlitas** [comment]
Looked through and changes look great. I tried searching some other random forms of "test", "testing", "/private.*test/", and I couldn't find anything, or think of any better search phrases. Sending back to @zepumph!
