### ISSUE TITLE
delete working-snapshot.sh?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#137]
What is chipper/bin/working-snapshot.sh?  Wondering if it's vestigial.  Created by @jonathanolson.

**Comment by jonathanolson** [comment]
Its purpose was for common-code repos (dot/kite/scenery). When they were broken by other common changes, it took a lot of time to track down (since I couldn't bisect across ~8 repos), so I found it easier to take snapshots of my repos when they were working, and when I came across a break, I could identify all of the common code commits that could have caused the break.

Things have been much more stable recently, so I'm less concerned and would be OK with deletion. working-snapshot.json would then be deleted from all applicable repos.

Any preferences?

**Comment by samreid** [comment]
I recommend deletion, but don't feel too strongly about it.

**Comment by pixelzoom** [comment]
I'll add @jonathanolson's description (above) to the code doc, let him decide whether to delete it since he's the sole user.  In it's current state, I really had no idea what it's purpose was or how to use it.

**Comment by pixelzoom** [comment]
Additional documentation added. Assigned to @jonathanolson to decide whether to keep or delete.

**Comment by jonathanolson** [comment]
Will opt to delete to keep things tidy. Haven't been using it lately.
