### ISSUE TITLE
Reduce size of strings in built sims

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/chipper#1377]
We noticed in a build of friction 1.6 that the translated strings add about 1.6 MB to the "_all" built file. The a11y strings are not translated and are duplicated for every language.

Also, the keys are really long which probably takes up extra space. Maybe we could add compression or the structure of string files could be improved.

**Comment by samreid** [comment]
We use Apache gzip compression, so likely not all of this 1.6MB is transmitted over the wire.

**Comment by samreid** [comment]
@jonathanolson says everything we do to compress is helpful. So we could change data structures or compress things.  This will be valuable with a11y strings in particular.  We will need to investigate the best way to do this.  Perhaps nesting or collapsing related tree items would be good.  Another improvement would be to reverse the data structures, so the string keys are only indicated once.  Like:

```
{
  mySimulation:{
     screen1:{
        en: 'Title',
        ja: 'Other title'
     } 
  } 
}
}
```

This will also help with disk space.

This issue is large enough to be for a subteam.

Story Point Poker:

You to Everyone (May 11, 2023, 12:09 PM)
5
 
John Blanco to Everyone (May 11, 2023, 12:09 PM)
5
 
Jesse Greenberg to Everyone (May 11, 2023, 12:09 PM)
13
 
Michael Kauzmann to Everyone (May 11, 2023, 12:09 PM)
13
 
Jonathan B Olson to Everyone (May 11, 2023, 12:09 PM)
5
 
Marla S. to Everyone (May 11, 2023, 12:09 PM)
5
 
Matthew Blackman to Everyone (May 11, 2023, 12:09 PM)
5

@zepumph indicates this is a far-reaching issue because it spans rosetta, the build server, the sim side, etc. How could this get done in one iteration?

@samreid based on that discussion, I will upgrade to a 13.

**Comment by jonathanolson** [comment]
Have a solution in the stringMap-encoding branch, https://github.com/phetsims/chipper/blob/stringMap-encoding/js/common/stringEncoding.js is the file to review.

I'm currently getting results in the range of:

- acid-base-solutions _all.html 4.38 => 2.75MB (major), _en.html 2.48 => 2.47MB (trivial)
- circuit-construction-kit-dc _all.html 4.61 => 3.12MB (major), _en.html 2.83 => 2.82MB (trivial)

Gzipped improvements are much more modest, so it won't help us too much on loading time.

Currently, the decode step is taking about ~20ms, decoder adds ~1kB uncompressed JS.

Ready for code review (before merge to main, I'd also like to do comprehensive testing)

**Comment by marlitas** [comment]
@jonathanolson is there someone you'd like to do the code review for this? I just saw no one was assigned so wanted to make sure it didn't get lost.

**Comment by jonathanolson** [comment]
I'll be looking into pako compression, to see whether we can improve things without hurting over-the-wire gzipped compressed size.

I'll be using CCK-DC as an example.

Normal total size: 4836814 bytes, gzipped (over-the-wire): 1252270 bytes
With string encoding approach: 3269955 bytes, gzipped (over-the-wire): 1207772
Difference: -1566859 bytes, gzipped (over-the-wire): -44498

**Comment by jonathanolson** [comment]
Strings section normal: 1890396, gzipped: 194461
With encoding: 323537, gzipped: 150521

**Comment by jonathanolson** [comment]
pako-inflate minified: 20819
Strings section normal, pako-compressed: 194449
Strings section encode, pako-compressed: 150509

Packaged:
pako + pako'ed normal: 215268, gzipped: 201657
pako + pako'ed encoded: 171328, gzipped: 159081

**Comment by jonathanolson** [comment]
Summary: for the strings contribution to the file size (including all decoding code's size):

For a downloaded sim (static file size):

- current: +1846 kB
- my encoding: +316 kB
- pako: +210 kB
- my encoding AND pako: +167 kB

For loading a sim from our website (gzipped):

- current: +190 kB
- my encoding: +147 kB
- pako: 197 kB
- my encoding AND pako: 155 kB

**Comment by jonathanolson** [comment]
pako-inflate will take up 7.2 kB, so adding pako on top of my encoding doesn't really change the gzipped size of the actual data.

**Comment by jonathanolson** [comment]
Code golfing CCK-DC with pako a bit gives me https://bayes.colorado.edu/dev/olsonjb/compressed-example.html (1635177 bytes, 1229869 gzipped).

That "limit" example is 34% of the current raw file size, and 98% of the current gzipped file size. Compared to the "encoded" variant, it is 50% (~50.006) of the improved raw file size, and 102% of the improved gzipped file size.

I don't yet have a good measurement for how much time the decoding takes. I'll ask about whether it's worth it to explore the "compress everything" approach.

**Comment by jonathanolson** [comment]
It is taking about 200ms extra to do the decoding.

**Comment by jonathanolson** [comment]
Pending on https://github.com/phetsims/rosetta/issues/384#issuecomment-1851219188.

**Comment by jbphet** [comment]
The Rosetta issue is now closed, you can feel free to move forward with this, BUT...

I noticed during my testing that there is no English string map file for graphing-slope-intercept.  As for as I could tell, other sims are fine.  I'm not sure why this one is unique in this regard, but I thought you should know about it.

**Comment by jonathanolson** [comment]
Enabled string maps by default! MP is aware of the graphing-slope-intercept problem. Presumably any issues will be caught by RC/production builds in the future. Closing.
