### ISSUE TITLE
Enable lint rule `require-atomic-updates`

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1382]
From https://github.com/phetsims/chipper/issues/814#issuecomment-838724968 we agreed to enable the lint rule "require-atomic-updates", but there are 6 offenses at the moment, currently all in rosetta.  They should be fixed or have the lint rule disabled for each occurrence, and the rule in chipper should be turned on.  @jbphet can you please take a look?

**Comment by samreid** [comment]
I enabled the rule in the root eslint.config.mjs and will assign file authors that may wish to address these.

**Comment by zepumph** [comment]
Thanks for turning this rule on. I went through all usages of this disabling. I believe that each one potentially holds the risk that the rule is trying to warn against, but in practice I couldn't find any that I would want to refactor or change. I'm glad this rule is on for new development, because it will be good to understand this awkward async condition before commit, but even then I may just disable these.

I recommend closing this issue as is, but would appreciate other assignees to look through usages they are familiar with just in case.

Thanks again.
