### ISSUE TITLE
Code comment results in getStringMap failure

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1401]
Discovered in https://github.com/phetsims/graphing-lines/issues/141

In GLSymbols.ts, I had this comment:

```ts
//TODO https://github.com/phetsims/graphing-lines/issues/140 use GraphingLinesStrings.symbol.*StringProperty
const GLSymbols = {
  b: MathSymbolFont.getRichTextMarkup( GraphingLinesStrings.symbol.intercept ),
  m: MathSymbolFont.getRichTextMarkup( GraphingLinesStrings.symbol.slope ),
  x: MathSymbolFont.getRichTextMarkup( GraphingLinesStrings.symbol.x ),
  y: MathSymbolFont.getRichTextMarkup( GraphingLinesStrings.symbol.y )
};
```

That comment results in this build error, reported by CT in https://github.com/phetsims/graphing-lines/issues/141:

> % cd graphing-lines
> % grunt
> ...
> Webpack build complete: 5288ms
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION]: Missing string information for graphing-lines symbo
> ...

Removing the comment makes the error go away.    So I suspect that getStringMap.ts is looking at comments in addition to runnable code.  Is this expected?

**Comment by jonathanolson** [comment]
I guess expected but undesirable, it isn't filtering out comments. We'd need to run a fill JS/TS parse in order to properly do so (think comment-like characters in backtick string literals).

Thoughts on how helpful that would be? (I'm imagining a decent chunk of initial work, and some continuing overhead). We can't use the minified output, it will mangle the `GraphingLinesStrings` in this case.

**Comment by pixelzoom** [comment]
To resolve https://github.com/phetsims/graphing-lines/issues/141, I rewrote the comment in GLSymbols.ts so that it does not cause getStringMap to fail.
