### ISSUE TITLE
Restarting '/Users/samreid/.npm-global/bin/grunt transpile --no-respawning'

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1521]
On a pull, my transpiler watch process said:

```
Restarting '/Users/samreid/.npm-global/bin/grunt transpile --no-respawning'
```

Not sure why. @zepumph saw something like this previously. Here is the context:

```
Successfully compiled aqua/js/local/puppeteerPage.js with swc (293.43ms)
Successfully compiled aqua/js/server/ContinuousServer.js with swc (203.8ms)
Successfully compiled aqua/js/server/playwrightCTClient.js with swc (212.18ms)
Successfully compiled aqua/js/server/puppeteerCTClient.js with swc (215.75ms)
Successfully compiled perennial-alias/js/eslint/config/util/rootRules.mjs with swc (51.31ms)
Successfully compiled scenery/js/nodes/Node.ts with swc (138.69ms)
Successfully compiled perennial-alias/js/eslint/config/util/rootRules.mjs with swc (5.06ms)
Successfully compiled scenery/js/nodes/Node.ts with swc (45.14ms)
Restarting '/Users/samreid/.npm-global/bin/grunt transpile --no-respawning'
Running "transpile" task
Transpiling code for 204 repositories, split into 3 chunks...
Successfully compiled: 2875 files with swc (948.68ms)
Watching for file changes.
Successfully compiled: 4151 files with swc (277.53ms)
Watching for file changes.
Successfully compiled: 4238 files with swc (238.45ms)
Watching for file changes.


```

**Comment by samreid** [comment]
This happened again on a pull today:

```
Successfully compiled perennial/js/common/browserPageLoad.js with swc (481.46ms)
Successfully compiled perennial/js/common/build.js with swc (516.45ms)
Restarting '/Users/samreid/.npm-global/bin/grunt transpile --no-respawning'
Running "transpile" task
Transpiling code for 203 repositories, split into 3 chunks...
```

**Comment by zepumph** [comment]
@samreid and I run into this a fair bit. It doesn't seem too problematic on the surface, but actually this is quite inefficient and scary. Grunt is watching some files for changes, and restarts the process when the files change. We don't want to overload `--watch` since grunt already owns it, and by the time we get to our grunt file, it has been processed.

I worry that this is catching an error in our transpiler silently, and just gracefully restarting. We should create a new option for now, without removing support for --watch, and see how things improve.


`--watching`
`--live`
`--auto`
`--sink`
`--listen`
`--continuous`
`--monitor`
`--watch-dog`
`--spidy-sense`
`--watchzilla`
`--guardian-angel`
`--ninja`

------------------

We'll go with `--live` for now.

**Comment by samreid** [comment]
Fixed in the commits and in the side issue https://github.com/phetsims/chipper/issues/1528. I believe this allowed us to remove the workaround https://github.com/phetsims/perennial/commit/9ead48a5bd6066d05ed9a78e3c662e5e6b97f24d and I have done so. @zepumph can you please spot check review and double check on https://github.com/phetsims/perennial/commit/9ead48a5bd6066d05ed9a78e3c662e5e6b97f24d in particular?

**Comment by zepumph** [comment]
Amazing! Thanks so much
