### ISSUE TITLE
should common-code repos with demo apps be included in active-sims?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#169]
I frequently use grunt-all.sh to test that changes don't affect the ability to build sims.  That script (and others) read the active-sims file, which currently includes only simulations in active development.  I've tried to run 3 demo apps for common-code repos recently (sun, vegas, scenery-phet) and found them all broken, with the same error.  So perhaps we should add common-code repos with demo apps to active-sims, so that we catch problems like this sooner.

**Comment by pixelzoom** [comment]
Example of the problems I've recently encountered:

https://github.com/phetsims/scenery-phet/issues/172
https://github.com/phetsims/sun/issues/193
https://github.com/phetsims/vegas/issues/45

**Comment by ariel-phet** [comment]
@pixelzoom - any downside to including these repos?

**Comment by pixelzoom** [comment]
No downside other than the semantic glitch that common-code demo apps are not sims, and will in a file named active-sims.

**Comment by aaronsamuel137** [comment]
Actually, there is a downside to this. Currently, the way Rosetta identifies a sim repo vs a common code repo uses active-sims. So I'd recommend against adding these repos to active-sims unless you can suggest another way for Rosetta to distinguish.

**Comment by samreid** [comment]
What will go wrong if Rosetta identifies a common code repo as an active sim?  Could we just hard-code a list in rosetta (custom logic) that knows to skip the common code repos?

**Comment by jonathanolson** [comment]
> Could we just hard-code a list in rosetta (custom logic) that knows to skip the common code repos?

That sounds like having three lists, instead of just active-repos and active-sims.

It still feels weird to me the way we make our common repos into "sims". Would it be weird to have a single demo sim?

**Comment by aaronsamuel137** [comment]
> What will go wrong if Rosetta identifies a common code repo as an active sim?

All of those common strings will appear under the "Sim Strings" section instead of the "Common Strings" section, and therefore the user will not get the warning that changing common strings will effect every translation. Also it would probably confusing to a user.

> Could we just hard-code a list in rosetta (custom logic) that knows to skip the common code repos?

Yes, this would be another option, we'd just have to remember to update the list if we create a new common repo.

**Comment by pixelzoom** [comment]
@jonathanolson said:
> That sounds like having three lists, instead of just active-repos and active-sims.

I agree, let's not pervert the semantics of active-sims (which I mentioned as a drawback).

**Comment by pixelzoom** [comment]
7/14/15 dev meeting, we decided to create a new file named `active-runnables` that contains all repos that have something that runs using the PhET framework.

**Comment by pixelzoom** [comment]
Some scripts and automated testing should be changed to use `active-runnables` instead of `active-sims`.

**Comment by samreid** [comment]
I’ll take a look at this after the meeting, and reassign to someone to double check.

**Comment by samreid** [comment]
I created active-runnables above and updated the scripts to use it where appropriate (specifically, everywhere except rosetta).

I'm testing with http://localhost:8080/chipper/tests/test-sims.html?loadOnly and it seems like the new repos are being tested properly.

I also tested that the new repos are hit by grunt-all.sh.

Some minor issues: I wasn't sure about projectile-motion. I added it to active-runnables since it has a sim_en.html but I'm not really sure what is going on there.
Vibe has a test html that uses require.js etc but does not match the naming convention.
Litmus is failing

Can someone review my changes above?  Any other tests that should be run?

**Comment by pixelzoom** [comment]
I'll take a look.

**Comment by pixelzoom** [comment]
Inspected and ran a few tests. Looks great. Closing.

**Comment by pixelzoom** [comment]
Litmus built fine for me. Are you up to date?

Reported vibe build failure in https://github.com/phetsims/vibe/issues/16.

**Comment by samreid** [comment]
My litmus is building now.
