### ISSUE TITLE
issues with reportUnusedImagesAndAudio.js

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#204]
Noted when reviewing #178.

1. The point at which this task is called seems odd, see #203 

2. Why is this separate from createSimSpecificThirdPartyReport?  It seems like it's an important part of that report, and there would be some value to having the entire resource report implemented in 1 task, and registered in Gruntfile.js (as a utility task).

3. The names of the other related tasks begin with "create"; createSimSpecificThirdPartyReport, createCompositeThirdPartyReport.  Why is this task named so differently?   And why make the name specific to images and audio, when other licensed resources may be needed in the future?

**Comment by samreid** [comment]
> The point at which this task is called seems odd, see #203

This is not a task.  Also, in #203 I described why the task is run then:

> Running the require.js build step is the only way to determine which images & audio are actually used by a simulation.

Next question was:
> Why is this separate from createSimSpecificThirdPartyReport?

Maybe it makes sense to include this with createSimSpecificThirdPartyReport, but we decided we always wanted to report an error when a sim is built that didn't use all of its images & audio, see https://github.com/phetsims/chipper/issues/172

> The names of the other related tasks begin with "create"; createSimSpecificThirdPartyReport, createCompositeThirdPartyReport. Why is this task named so differently?

As aforestated, this is not a task.  It is a function.

> And why make the name specific to images and audio, when other licensed resources may be needed in the future?

Images and audio are the only file types that we can determine if they are actually used by the simulation through require() statements since they are the only resources loaded through plugins.

Now that you have more context, it would be good to discuss next steps.

**Comment by pixelzoom** [comment]
> Running the require.js build step is the only way to determine which images & audio are actually used by a simulation.

Curious about how this is implemented. Are the image and audio plugins compiling a list?

> Images and audio are the only file types that we can determine if they are actually used by the simulation through require() statements since they are the only resources loaded through plugins.

They are *currently* the only file types. Can't imagine a future with video resources? Or some new type of animation file format similar to Flash swf?  Just trying to be forward-looking here and not box us into this being for images and audio only.

**Comment by pixelzoom** [comment]
Discussion about "images and audio" naming moved to #212.

Closing.
