### ISSUE TITLE
does anything in the build process need complete string entries?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#264]
Why does anything outside of string.js need to know about the complete entry for a string key? Why doesn't string.js just build a map between key and value, so that we don't have someArray[key].value appearing in other code? (build-server.js excepted.)

@jonathanolson Handled the conversion to the new string.json format, so I'd like to hear his opinion.

**Comment by pixelzoom** [comment]
To be clearer... When the file format was changed, it seems like the change should have been completed isolated in string.js.

**Comment by jonathanolson** [comment]
Well it can't be contained to string.js, since afterRequirejsBuild handles the strings for chipper builds.

".value" seems to be in build-server (directly reads the string file), generateREADME (directly reads the string file), afterRequirejsBuild (reads string files for the build), and the string plugin (for obvious reasons).

I wasn't aware that the build-server and generateREADME were dealing directly with those, and mostly to get sim titles. Are you advocating for consolidating Node.js string lookups?

Otherwise, I'm not sure what really should be done. I'm not sure what would be added to string entries, but it's conceivable that various parts of the build process could need it.

Can you clarify (a) what is wrong, or (b) what is desired, or is this just a question?

**Comment by pixelzoom** [comment]
> Can you clarify (a) what is wrong, or (b) what is desired, or is this just a question?

As far as I can tell, the build process only uses "value".  So my question is, why doesn't string.js build a map from key -> "value", instead of key -> entry, so that other parts of the build processes didn't have to be modified to know about "value"?

**Comment by pixelzoom** [comment]
Discussed with @jonathanolson and I now understand what's going on here. In build mode, string.js defers the bulk of the work to afterRequirejsBuild.js. Very confusing, not well encapsulated.  But I guess we'll leave this as is for now.
