### ISSUE TITLE
Investigate the google closure compiler

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#293]
At a Boulder JavaScript meetup yesterday, one of the lightning talkers suggested swapping out the uglify2 minifier for the google closure compiler.

I tried it and noticed the following:
(1) (Helpful?) Warning messages that indicated missing JSDoc entries, unreachable code, suspicious code, etc:

```
./bending-light-none.min.js:21372: WARNING - parameter node does not appear in <anonymous>'s parameter list
    getSerializedFocusOrder: function() {
                             ^

./bending-light-none.min.js:22010: WARNING - Suspicious code. This code lacks side-effects. Is there a bug?
        if ( this.rendererOptions ) {
        ^

./bending-light-none.min.js:22197: WARNING - References to the global RegExp object prevents optimization of regular expressions.
        rv = parseFloat( RegExp.$1 );
                         ^

./bending-light-none.min.js:22203: WARNING - References to the global RegExp object prevents optimization of regular expressions.
        rv = parseFloat( RegExp.$1 );
                         ^

./bending-light-none.min.js:22616: WARNING - parameter fill does not appear in <anonymous>'s parameter list
        setStroke: function( stroke ) {
                   ^

./bending-light-none.min.js:26994: WARNING - Suspicious code. This code lacks side-effects. Is there a bug?
          if ( this.displayUpdateOnEvent ) {
          ^

./bending-light-none.min.js:29797: WARNING - Misplaced function annotation. This JSDoc is not attached to a function node. Are you missing parentheses?
        this.events.trigger( 'layoutFinished', dx, dy, width / scale, height / scale, scale );
        ^

./bending-light-none.min.js:41961: WARNING - attempted re-definition of type Screen
found   : function (new:Screen, string, (Node|null), ?, ?, (Object|null)=): undefined
expected: function (new:Screen): ?
  function Screen( name, homeScreenIcon, createModel, createView, options ) {
  ^

./bending-light-none.min.js:42667: WARNING - parameter - does not appear in Prism's parameter list
  function Prism( shape, typeName ) {
  ^

./bending-light-none.min.js:43780: WARNING - parameter button does not appear in contentAppearanceStrategy's parameter list
  var contentAppearanceStrategy = function( content, interactionStateProperty, options ) {
                                  ^

./bending-light-none.min.js:55490: WARNING - unreachable code
      return;
```

(2) Using these parameters `--language_in=ECMASCRIPT5 --compilation_level=ADVANCED` the minified HTML file is about 13.7% smaller download.

> Uglify2
1112937 Aug 20 00:12 bending-light_en.html

> Closure Compiler
960205 Aug 20 00:14 bending-light_en.html

(3) The closure compiled version doesn't run.  I get 

> TypeError: Cannot read property 'OM' of undefined at [...]

![image](https://cloud.githubusercontent.com/assets/679486/9383883/90c0298a-4709-11e5-8c09-5ac5ec98e4ab.png)

I am unsure what steps would need to be taken to get this compiling

(4) the closure compiler step took 22 seconds.  I was unable to easily measure the uglify2 time as it is inlined into the requirejs task at the moment.

(5) the google closure compiler reportedly can do type checking, but I'm not sure why I didn't see any type errors, or whether other flags or work is required to get there.

(6) aside from smaller code, the google closure compiler reportedly performs some optimizations, such as changing while loops to for loops, etc. I was unable to test if these have any significant impact on the performance of our code at runtime since I was unable to run the closure compiled version.

**Comment by pcj** [comment]
A few comments:

* Use `--compilation_level=SIMPLE` to optimize without making code-breaking changes.

* Changing from uglifyjs to closure-compiler only for the purpose of making your code smaller is probably not worth it.  IMHO you should consider it if: (1) you want static typing, (2) you want to use the closure javascript library.  

* The closure compiler only knows about types if you tell it what the types are.  These are communicated to the compiler via JSDoc-like comments.  See https://developers.google.com/closure/compiler/docs/js-for-compiler.  Note that the JSDoc tag syntax is not synonymous with the tags used by JSDoc3 or other documentation generation tools, though there is seemingly significant overlap.

* ADVANCED mode is not trivial to implement, because it requires you do be explicit about dependencies on third-party libraries (see discussion of externs https://developers.google.com/closure/compiler/docs/api-tutorial3) and explicit about how your library code is used (the parts of your code that are used by other modules or whatever).

I'm not sure the sequence of events that occur in the HTML file to get the bending-light example up and running, but most likely there's some piece of code outside what you compiled that trying to invoke whatever name is thinks it should be, maybe `new BendingLight().run()` or something like that.  But after ADVANCED compilation, that name no longer exists, it could be something like `new k().t()`.  Of course, there is no way for external code to know what the new name is, so you need to "export" the entry point of your closure compiled code.

For ex, here's how my app boots.

```
$(function() {
  v1.app.main();
});
```

But those symbols v1.app.main are "exported" into the global namespace by the closure library function `exportSymbol`:

```
/**
 * Main entry point for the browser application setup.
 */
v1.app.main = function() {

  // Increase stacktrace limit 
  Error['stackTraceLimit'] = 150;

  // Create the webapp client and build it into the body tag.
  var app = new v1.app.Desktop('v1');
  app.build('body');

};

goog.exportSymbol('v1.app.main', v1.app.main);
```

Everything within the v1.app.main function, including the reference to the Desktop application class and all the 150 or so dependent files that it uses are all ADVANCED compiled together as a single obfuscated lump. 

* 22 sec sounds typical for a cold JVM.  I use a tool called plovr that keeps the compiler JVM running between compiles, which makes a huge time difference for subsequent compiles.  Mine takes about 28sec cold but about 4s with a warm JVM.

* If this all sounds like a big pain in the ass, that's because it is.  It's hard to scale javascript development beyond a certain point before you really need static typing.   If you're at that point, go for it.  Bolting on static typing to a language that fundamentally does not have explicit types is not a trivial undertaking.    Closure compiler is not the only game in town.  Check out facebook's flow product as well.

**Comment by pixelzoom** [comment]
8/20/15 dev meeting notes:

Possible advantages:

• better type checking
• better error checking
• faster downloads (smaller minified code)
• faster running code

Possible disadvantages:

• might require moving away from RequireJS, which would require major code changes
• slower build times (unless you keep the JVM running)

**Comment by pixelzoom** [comment]
> If this all sounds like a big pain in the ass, that's because it is.

-1 using this.

**Comment by samreid** [comment]
@jonathanolson said that the closure compiler would likely have difficulty in dealing with our dynamically generated properties or methods.

**Comment by samreid** [comment]
Consensus from meeting: We decided not to pursue this at the moment.
