### ISSUE TITLE
change repo.name convention to repo.title

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#340]
Change this in chipper and throughout sims.  Do it for S2105R.

**Comment by aaronsamuel137** [comment]
There is a line in rosetta that looks for repo.name which will need to be changed. This is how Rosetta looks up that sim title to display (i.e. Concentration Strings). See routes.js line 292.

**Comment by pixelzoom** [comment]
It's also hardcoded into build-server.js, line 352:

`simTitleKey = simName + '.name';`

**Comment by pixelzoom** [comment]
https://github.com/phetsims/chipper/commit/83709494db922cafd8c9d32d1441f188bc588469 was also involved in this issue, and incorrectly labeled in its commit message.

**Comment by pixelzoom** [comment]
Changes completed.  I verified that all sims build using `grunt-all.sh`. 

I also made the changes identified above in rosetta and build-server. @aaronsamuel137 could you please verify that I didn't mess anything up?  Thanks.

**Comment by pixelzoom** [comment]
This is a breaking change, so I announced to the Google Group:
https://groups.google.com/forum/#!topic/developing-interactive-simulations-in-html5/fhnBcrUbAVs

**Comment by aaronsamuel137** [comment]
A few potential issues here:

1. Looks like molecule-shapes already had a string with the key "molecule-shapes.title", with value "Model", so now it has 2 strings with the same key. Not sure if other sims are in the same boat, just happened to notice this because it is in Rosetta and suddenly had the header "Model Strings".

2. This will require republishing of any sims (like molecule-shapes) that are already published. Because the build-server code doesn't have a fallback to use .name instead of .title, it won't be able to find the sim title on older shas. Or we could add a fallback in build-server.

It also makes me aware of another issue with Rosetta: if you change the string keys in master, Rosetta will be looking at inconsistent strings. It will take the strings keys in a published version and look for the English values in current master. This is probably something that will need to be fixed in Rosetta. However, it is somewhat difficult to address since the way it is set up now, Rosetta doesn't know what shas to look for for the matching version of the english strings.

**Comment by aaronsamuel137** [comment]
Regarding the rosetta issue, looks like it is solvable by extracting the correct sha from the source code. I'll create a new issue for this in rosetta.

**Comment by pixelzoom** [comment]
I fixed the issue in molecules-shapes. It has this entry for the "Model" screen name, which seems a little wrong:

```js
  "molecule-shapes.title": {
    "value": "Model"
  },
```

I changed both screen names to use the "screen." key convention, so they now look like this:

```js
"screen.model": {
    "value": "Model"
  },
  "screen.realMolecules": {
    "value": "Real Molecules"
  },
```

Tested in both molecule-shapes and molecule-shapes-basics.

**Comment by aaronsamuel137** [comment]
I added a fallback for .name in build server and republished sims for the rosetta beta test.

Molecule Shapes will need to be republished on the live site in order to work properly with rosetta. (It will almost work as is, but will show up as "Model Strings" instead of "Molecules Shapes Strings")

Anything else to do here?

**Comment by pixelzoom** [comment]
Wondering why the fallback is needed for Rosetta?  Is it a permanent fallback, or something that you're planning to remove?

**Comment by aaronsamuel137** [comment]
I guess it is unnecessary once all the MS is republished, so I can remove it then.

**Comment by pixelzoom** [comment]
OK.  I'll leave it up to as to whether to leave this issue open until then, or to just add a TODO item to the source code.

**Comment by aaronsamuel137** [comment]
Removed from build-server. Closing
