### ISSUE TITLE
[build-server] Initial logging

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#352]
1. The defaultOptions for -h or --help are never used.
2. Probably not an issue, but if --silent is passed in, it will still spit out console errors if you added an unrecognized option, or if you provided a help option.
3. console.error should be used on an unrecognized option, so it goes to stderr.
4. It's probably worthy of a log line if the "configure email server" conditional fails, triggering emails to not be sent? (say emailTo was null or something accidentally after we updated - how long before we notice no emails are being sent?)

Review: https://github.com/phetsims/chipper/issues/141

**Comment by aaronsamuel137** [comment]
I've addressed numbers 3 and 4. Regarding 1, -h and --help need to be in default options, otherwise it will say "unrecognized option" if you try to use them.

Also, in practice the only option that is used is --verbose. When run as an init script, the logging is set up to go to rosetta.log by default. Do you think it is worth is to leave these options in place, or remove them? They are mostly just there since I copied them over from rosetta.

Assigning to @jonathanolson for feedback and review.

**Comment by jonathanolson** [comment]
> Do you think it is worth is to leave these options in place, or remove them? 

--help is always nice to have. up to you for the others.

**Comment by aaronsamuel137** [comment]
Decided to remove silent and logFile, since in practice we are handling these cases differently.

Assigning to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Sounds good.
