### ISSUE TITLE
[build-server] Rosetta push/pull handling of merge conflicts

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#365]
It seems right now all it will do is log a warning if addToRosetta fails due to merge conflicts since it uses execWithoutAbort (it will continue on with the build).

The unlikely but serious failure:
1. Push fails when network/GitHub is down
2. Someone reformats simInfoArray.json before the next time the same sim is built
3. Merge Conflict

The more likely but less serious:
1. Push fails when network/GitHub is down, so sim isn't translatable

Does this warrant an email or build failure?

Review: https://github.com/phetsims/chipper/issues/141

**Comment by aaronsamuel137** [comment]
The reason I used execWithoutAbort is because technically the git push will "fail" if there are no changes made, which happens all the time if you are deploying a translation and not a totally new sim.

Though it looks like the check ```if ( simInfoArrayString !== contents ) {``` should handle this case, so maybe it is safe to use exec here instead. I might have added this check after I used execWithoutAbort and forgot to update it.

I'll try using exec for now and see if it causes problems.

**Comment by aaronsamuel137** [comment]
Forgot to reference the issue, here is the commit: f1e98e68dec90e8866ecb02359f6045fbd3b1eb8

**Comment by aaronsamuel137** [comment]
On second thought, I decided to go with execWithoutAbort and send and email for now. Assigning to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks good, thanks.
