### ISSUE TITLE
[build-server] dependencies.json created twice?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#370]
As noted briefly in https://github.com/phetsims/chipper/issues/366, it seems dependencies.json is first created from the SHAs sent to us, but then it might be overwritten by the build process (since that also outputs dependencies.json?).

Also, the repos object is modified (deleting the comment), which we may not want to do. I think dependencies.json is first written BEFORE the repos object is modified, but making a local copy of the repos object (where the comment needs to be deleted) might be the safest option.

Review: https://github.com/phetsims/chipper/issues/141

**Comment by aaronsamuel137** [comment]
dependencies.json is created once for internal use by the build server, and once in the build itself. It is not overwritten because it is created in two different places.

The build server creates this file so it can call grunt checkout-shas, which needs to be done before the actual build. Does this make sense? Anything you think should be changed here.

**Comment by aaronsamuel137** [comment]
>making a local copy of the repos object (where the comment needs to be deleted) might be the safest option.

I've made this change.

**Comment by aaronsamuel137** [comment]
Assigning to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks good, thanks!
