### ISSUE TITLE
"grunt create-sim" should adjust copyright comments

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#408]
`grunt create-sim` should replace copyright comments with 

`// Copyright <currentYear>, University of Colorado Boulder`

It currently just copies the simula-rasa files without change.

Assigning to @samreid to see if he has thoughts on the best way to handle this.

**Comment by samreid** [comment]
Not sure what is best, but I'll brainstorm some ideas for discussion:

1. Leave the copyright statement as-is since the new sim is a "derived work" from simula rasa.  Though this could conflict with grunt update-copyright-dates run later on.
2. Update the simula-rasa dates once a year on the first business day after Jan 1, so newly created sims will get the right dates.  Though these would get overwritten by anyone running grunt update-copyright-dates later on.
3. Run a script that patches the date after running simula-rasa and after checking in files (so git dates can be used), I believe the script is called `update-copyright-dates`.
4. Add a manual step that prints out after running simula-rasa to remind the developer to update the dates
5. Replace all dates in simula-rasa with variables like $YEAR$ and put the replacement in the rule. Though this could conflict with our linting rules.

1, 2, 5 seem like they have inconvenient defects, and perhaps (3) or (4) are in the sweet spot of the cost-benefit analysis curve?

**Comment by pixelzoom** [comment]
How about just a global replace of "// Copyright *, University of Colorado Boulder" with (for example) "// Copyright 2015, University of Colorado Boulder" ?

**Comment by samreid** [comment]
In your example, is the * a literal `*` or a placeholder for a date, or a placeholder for a date | date range?

**Comment by pixelzoom** [comment]
The '*' is a placeholder for an set of chars. Not a valid JS regular expression, but hopefully you get the idea.  Or if you prefer, replace any line that starts with "// Copyright \d\d\d".

**Comment by samreid** [comment]
We could insert a line on line 95 of createSim.js:
```js
contents = updateCopyright( contents );
```
where updateCopyright fixes the years in the copyright statement.  I'll leave this assigned to myself to do so.

**Comment by pixelzoom** [comment]
I'm working on it now.

**Comment by pixelzoom** [comment]
Tested by running:

`grunt create-sim --name=foo --author="Some Guy" --title="Foo!"`

Inspecting the copyright comments, they are:

`// Copyright 2015, University of Colorado Boulder`

And the created sim passes lint and runs in requirejs mode. I was unable to confirm that it builds, because the PhET build process fails if a sim is not a GitHub repo.

Assigning to @samreid to review.

**Comment by samreid** [comment]
Looks great, closing.
