### ISSUE TITLE
'grunt deploy-rc' should fail if there are working copy changes

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#435]
`grunt deploy-rc` delegates a dev build to builder-server. It should fail if you have working copy changes that are not pushed.   Currently it's possible to test your working copy, forget to push, and deploy-rc.

If there are any use cases inhibited by failing, then add a grunt option that essentially says "I know that I have unpushed changes, but do the deploy-rc anyway".

**Comment by samreid** [comment]
@jbphet volunteered, thanks! :stars:

**Comment by jbphet** [comment]
I've implemented a pass at this, but would like some pre-review before committing from someone with a bit more recent chipper experience so that I make sure that I'm being consistent with the current big picture design of chipper.  @pixelzoom has done the most work in here, but other devs may also be able to do it if he's not available.  I'm thinking I'd need 0.5 to 1.0 hours of someone's time.  Assigning to @ariel-phet to decide who I can lean on for this.

**Comment by jbphet** [comment]
There seems to be some contradiction between what this issue is specifying and what is described in https://github.com/phetsims/phet-info/blob/master/sim_deployment.md in the "Steps to publish a rc" [sic] section.  In that document, it doesn't say anything about setting up a dependencies.json file and checking out the listed SHAs when creating the first RC from a branch, so the dependencies could very well be on the master branch.  I don't personally do release candidates this way - I explicitly make sure that a dependencies.json file is present and that the associated SHAs are checked out, but perhaps others do things differently.  I'm going to mark this issue for discussion in dev meeting so that we can decide whether we really want to abort a ```deploy-rc``` if dependencies are on master.  If so, we'll need to update the documented process steps.

**Comment by samreid** [comment]
I presumed that creation of a 1st RC would entail automatic creation of the 1st version of the dependencies.json, though I am not opposed to @jbphet doing it the way he described as an extra "safety net".

**Comment by pixelzoom** [comment]
`grunt deploy-dev` should *not* fail if dependencies are on master.  For the first version of a release branch (eg, 1.1.0-rc.1 on branch '1.1'), having repos on master is expected and dependencies.json (if it exists) is not relevant.  And at any point during the RC process, we may choose to use master of dependencies if that's determined to be more effective than branch-and-patch.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/chipper/issues/435#issuecomment-184833699, @jbphet said:
>  In that document, it doesn't say anything about setting up a dependencies.json file and checking out the listed SHAs when creating the first RC from a branch, so the dependencies could very well be on the master branch. I don't personally do release candidates this way - I explicitly make sure that a dependencies.json file is present and that the associated SHAs are checked out, but perhaps others do things differently.

I'm confused by this, because there should be no need to manually create or edit dependencies.json.
Could you elaborate on how you "explicitly make sure that a dependencies.json file is present"?

**Comment by jonathanolson** [comment]
> For the first version of a release branch (eg, 1.1.0-rc.1 on branch '1.1'), having repos on master is expected and dependencies.json (if it exists) is not relevant.

Presumably we want the sim repo itself to NOT be on master at this time (1.1 would be checked out), and all OTHER repos wouldn't matter.

For the long-term, I'd still recommend we have single grunt commands for each operation, instead of having multiple steps. The steps I had to follow for maintenance releases (https://github.com/phetsims/yotta/issues/17#issuecomment-183092153) felt like a lot.

**Comment by jbphet** [comment]
Consensus at Feb 18 2016 dev meeting: Don't do the part about checking that sims are on master.

**Comment by jbphet** [comment]
@jonathanolson will review with me.

**Comment by pixelzoom** [comment]
.... and check that working copy changes are both committed and pushed.

**Comment by jbphet** [comment]
@jonathanolson and I discussed and decided to also add a ```dryRun``` flag that would check all preconditions but skip the actual build and deployment, as well as the commit of the dependencies.json.

**Comment by jbphet** [comment]
I reviewed most of the changes for this issue with @jonathanolson prior to committing them, but it would be good if he could review them in their final (for now) form and do some testing on OSX (I've only tested on Windows).  Assigning to him.

**Comment by jonathanolson** [comment]
Planning to test tomorrow, as I'll need to do maintenance releases anyways.

**Comment by jbphet** [comment]
In the case of the first RC on a branch, there may well be no dependencies.json file.  In this case, the code has been designed to check only the sim repo and *not* its dependencies for uncommitted and unpushed changes.

**Comment by jonathanolson** [comment]
Worked as expected during deployments. Thanks!
