### ISSUE TITLE
Standardizing JSDoc param syntax

### ISSUE THREAD

**Issue by andrewadare** [phetsims/chipper#465]
Since starting with PhET, I've dealt with some inconsistency annotating functions with `@param`. Syntax like `Array<Object>` or `Property<boolean>` felt natural and reminiscent of template/generic syntax for parametric types in other languages. 

But I've seen the dot used extensively in PhET code (`Property.<string>`). The Google Closure Compiler [doesn't seem to favor that](https://developers.google.com/closure/compiler/docs/js-for-compiler#tags), but [JSDoc does](http://usejsdoc.org/tags-type.html). Who's more authoritative?

My vote (since I'm filing the issue) is to sidestep the ambiguity with arrays by using e.g. `Object[]` and to go with Google's syntax for other parametric types like Property.

I discussed this with @samreid and we decided it might be worth a brief discussion to get everyone on the same page (then move on with life).

**Comment by pixelzoom** [comment]
The format of param syntax was standardized some time ago after extensive discussion, and we decided in favor of JSdoc over Google Closure Compiler. The syntax is summarized by example in the "Code Style" section of "PhET Development Overview" at http://bit.ly/phet-development-overview.  Any inconsistencies in param syntax are likely due to code that predates standardization, or developers who are not following (or are not aware of) the standard.  

Not to say that we can't revisit this issue, but we should first identity what is to be gained. My feeling is that PhET already has a reasonable standard, and a large body of code that follows that standard. And we'd be better off putting effort into correction inconsistencies than hashing out another standard that essentially communicates the same information.

**Comment by andrewadare** [comment]
If this is something that's already settled, then in my opinion, it's worth mentioning in the dev guide more explicitly. If there are no objections, I'll make a brief addition to the guide that the at-param syntax is not entirely consistent between doc generation backends, and that JSDoc is the authoritative one where there are discrepancies.

**Comment by pixelzoom** [comment]
Reopening so we can make all developers aware of this, and decide what to do about inconsistencies.

**Comment by pixelzoom** [comment]
Discussed at 5/17/16 dev meeting, closing.
