### ISSUE TITLE
Factor out QUERY_PARAMETER_SCHEMA from initialize-globals.js

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#540]
From talking with @samreid and working on https://github.com/phetsims/phet-io/issues/878, the query parameter schema shouldn't be in initialize-globals, it makes the file large are clunky. We should take it out and put it in it's own separate file.

**Comment by zepumph** [comment]
@pixelzoom does this seem like a reasonable thing to do? Do you have an opinion?

**Comment by pixelzoom** [comment]
The file is < 400 lines, hardly "large and clunky". (If you want to see large and clunky, see Node or Sim.)

What's the advantage to taking QUERY_PARAMETERS_SCHEMA out of initialize-globals.js?  The doc for initialize-globals.js says "Initializes phet globals that are used by all simulations, including assertions and query-parameters", so it's not misplaced. Everyone (including non-developers) currently knows to look here for query parameters.  And there are currently no plans (that I'm aware of) to use QUERY_PARAMETERS_SCHEMA outside of initialize-globals.js.

If you did remove QUERY_PARAMETERS_SCHEMA from initialize-globals.js, then how do you propose to make it available to initialize-globals.js?  Hopefully not via a global, since creating globals is the responsibility of  initialize-globals.js.

Sounds like a non-problem to me.

**Comment by samreid** [comment]
I think it would be clearer if there was one file responsible for query parameters--this pattern has served us well for simulations (such as FBQueryParameters.js) and will serve us well for chipper. We would have done this long ago, but balked at having to add a new preload manually for each sim HTML (we can now do this automatically through `grunt generate-development-html`.) I agree that we are all "used to" the way it is now, but that doesn't mean it shouldn't be improved.  When training new team members, or sharing this information with groups outside of PhET, it will be clearer.  And once we get "used to" having the query parameters handled by a single file, it will be simpler for our team too. In my opinion, it is worth the cost of time to refactor and the cost of a new global variable.

**Comment by zepumph** [comment]
Tagging other developers to see if they have opinions, you can unassign once you have seen this/commented if you want.

**Comment by jonathanolson** [comment]
I'm ambivalent. Having separate preload files in a way is nice (files are more focused) and a query-parameter related name will be good, but means that I'll have to refer more closely to the ordering of preload files specified in build.json.

There are other places besides sims where initialize-globals is used, make sure to hit those if this is changed.

**Comment by pixelzoom** [comment]
If we do have a separate file, my inclination would be to name it phet-query-parameters.js, for symmetry with phetio-query-parameters.js.  But would the similarity of those names cause confusion?

**Comment by samreid** [comment]
Or name it "simulation-query-parameters.js"?  PhET-iO simulations will include both files.

**Comment by mattpen** [comment]
Encapsulating query-parameters in a separate file sounds good to me, but I don't have a strong opinion.

**Comment by zepumph** [comment]
It seems like there is a consensus that it would be a nice enhancement to the project. Marking as low priority and I will get to it when I'm bored or not busy (ha).

**Comment by zepumph** [comment]
I think I have come full circle on this. I'm not sure that this is entirely necessary. Implementing to me seems like we would add another preload that has a global that holds the schema, and then using that object and probably deleting it after QSM uses it to avoid clutter. I feel like this adds complexity without helping much.  What do people think?

**Comment by pixelzoom** [comment]
My opinion is unchanged from https://github.com/phetsims/chipper/issues/540#issuecomment-272044217:
> Sounds like a non-problem to me.

**Comment by samreid** [comment]
I'm fine to close this and leave things as they are.
