### ISSUE TITLE
interim conventions for naming release branches

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#587]
phet and phet-io brands are currently published out of separate release branches, and this is likely to be the case until PhET has more mature build/deploy tools and processes to support PhET-iO.

This issue describes interim conventions for naming release branches.  

I'll start with my understanding, which may be incorrect.  Here goes...

• Every release branch has a name of the general form `major.minor[.brand]`, where `brand` is excluded for brand=phet, and the "phet-io" brand name is mutated to "phetio".  Examples: 1.1, 1.1-phetio

• If phet and phetio brands are published at the same time, then there will be 2 branches with the same `major.minor` numbers, e.g. 1.1 and 1.1-phetio.  The 2 branches must be created using identical shas.

• The existence of branches with the same `major.minor` numbers (e.g. 1.1 and 1.1-phetio) implies that they were created with identical shas, and must be (manually) kept synchronized for maintenance releases.

• If phet and phetio versions are _not_ published at the same time, then we skip `minor` version numbers.  E.g. function-builder currently has release branches 1.0 and 1.1-phetio.  This implies that there was a 1.0 release for brand=phet, followed some time later by a 1.1 release for brand=phet-io.

• Continuing with the function-builder example... For a future release, if I published phet and phet-io brands at the same time, they would be in 1.2 and 1.2-phetio branches respectively, and would have identical shas.  If I published brand=phet, then brand=phetio sometime later, they would be in 1.2 and 1.3-phetio branches respectively.

• The above conventions are effective only if we all understand them, and don't make errors in applying them. 

Other developers, please correct/clarify this description.

**Comment by pixelzoom** [comment]
Another point related to patches:

• If 2 release branches share the same `major.minor` numbers (e.g. 1.1 and 1.1-phetio) then any patches must be applied to _both_ branches in order to satisfy the requirement that they be kept in sync.

**Comment by zepumph** [comment]
Plus 1 on the comment above, this is key. In the deploy docs I added in this section:

Step 1 Set up the codebase --> RC_subsequent/ Production:

>Maintenance Release: If there is a parallel brand that has the same minor number as your branch (i.e. 1.3 and 1.3-phetio), it means that these branches should have the same shas (not always true in practice, but mostly accurate, so check your shas). Make sure that all of your commits are cherry-picked onto that branch too (if they apply), so that the branches stay in sync.

I'm not sure how long this will have to be manually implemented before we make better build tools.

**Comment by pixelzoom** [comment]
Regarding patches, according to @jonathanolson via Skype:

> The last I've heard, there's an issue to figure out how to handle maintenance releases for phet-io. Every "batch" maintenance release (including fixes from patches) has totally ignored phet-io, and I was told explicitly it was fine to leave the phet-io versions with bugs.

So we have a branching scheme that relies on manual synchronization.  And a patch process with no support for synchronization.

**Comment by zepumph** [comment]
Here is a list of all of the branches that maintenance applies to across branches, please add more if I missed something. Basically there are 5 sims that have this problem. Of them, BASE, JT, and (soon to be) FAMB all have new phet-io versions out. BLL and CAF  are both so old that if we ever need to much of a maintenance release on them for a phet-io client, we would probably want to just give them a new version anyways, since so much has improved.


* BASE 1.2 1.2-phetio Maintenance releases have diverged since Jan 30th ish
* BLL 1.4 1.4-phetio Maintenance Releases have diverged since May 2016
* CAF 1.0 1.0-phetio, Maintenance releases have diverged since Sept 2016
* FAMB 2.1 2.1-phetio, 2.2 2.2-phetio Maintenance releases have diverged
* JT 1.3 1.3-phetio, totally deviated. 1.3-phetio is basically the same, but 1.3 has many new commits over months.


New (half-published/unpublished but soon to be with identical shas for the two branches)
* RIAW 1.3 1.3-phetio
* FAMB 2.3 2.3-phetio
* Plinko 1.1 1.1-phetio 

I guess I'm trying to say, that this is mainly a problem from here on, and the shortcommings of our maintenance to this point for PhET-iO are not substantial. We should try to come up with a system that is effective now.

**Comment by pixelzoom** [comment]
Deferred to next week's dev meeting when @samreid is present.

**Comment by pixelzoom** [comment]
6/29/17 dev meeting:
• Description in https://github.com/phetsims/chipper/issues/587#issue-237680549 is correct.
• Everyone has read and understood.

Closing.

**Comment by pixelzoom** [comment]
Regarding the "interim" nature of these conventions... The current conventions have problems that we'll need to live with for an unknown amount of time. We have a vague sense of where we’d like to be in the future (e.g. phet and phet-io published out of the same release branch).   But we can’t move forward without answers to the “big picture” questions in https://github.com/phetsims/phet-io/issues/1137#issuecomment-307514863, followed by a significant investment in the development of new build/deploy processes and tools.
