### ISSUE TITLE
a11y-view wrapper doesn't show duplicate alerts

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/chipper#614]
When two alerts alerts with the same content are announced back to back, the a11y-view wrapper doesn't show the second alert. I can see the second alert coming through scenery-phet/UtteranceQueue, and I can hear the alert with a screen reader so it seems like a bug with the a11y-view. @zepumph would mind looking into this at some point?

**Comment by zepumph** [comment]
I can repeat this easily. Go to an a11y view and press the restart button, wait for the alert to disappear and then press the reset button again. There will be no updated pdom.

**Comment by zepumph** [comment]
It looks like this isn't a problem with the a11y view, because it is identical to the `aria-live="polite"` paragraph in the pDOM (actually it is in a separate div with id of `aria-live-elements`). I think the issue is with AriaHerald, or something in between the UtteranceQueue.next() call and the actual DOM element. Notice this snippet, how everything is aligned nicely on the first press of the ResetAllButton. I am logging in the `UtteranceQueue` right before using `AriaHerald` to set the polite `p` tag.

![image](https://user-images.githubusercontent.com/6856943/31799047-4a26c010-b4e4-11e7-9565-32a8d858bb6a.png)


Then when I press the resetAllButton once again, this is what the image looks like.

![image](https://user-images.githubusercontent.com/6856943/31799063-6be8bd66-b4e4-11e7-87ff-654b64d6716f.png)

The first alert actually stays in the `p` tag until the next alert comes in, and then that empties the aria-live polite `p`!
This seems like it is a problem with AriaHerald. I will look further.

**Comment by zepumph** [comment]
Setting `withClear=true` option on `AriaHerald.announcePolite()`  did not fix this.

**Comment by zepumph** [comment]
Arg actually it turns out that `withClear` is true by default (because if you omit it from the `announcePolite` call then it is undefined, and if it undefined then it defaults to true, quite confusing. I wonder why that happens). Setting it to `false` fixes the problem. So it appears to be a problem with how `withClear` is handling duplicates? This is a strange hypothesis as I would expect AriaHerald to not have the granularity to determine if an alert is the same or different.

**Comment by zepumph** [comment]
I found it!!

What is happening is tricky. AriaHerald is only setting a property, and the Property's listeners are responsible for setting the actual element, but notice this check in the setter of Property:

```js
      set: function( value ) {
        assert && this.isValidValue && assert( this.isValidValue( value ), 'invalid value: ' + value );
        if ( !this.equalsValue( value ) ) {
          this._setAndNotifyListeners( value );
        }
        return this;
      },

```

So it doesn't notify listeners because it is the exact same value.

I'm not sure what the best solution would be for this, I'm also not sure why setting `withClear` to false fixes this problem.

**Comment by zepumph** [comment]
To sum up my findings from the above comments:
This is a problem with how AriaHerald is handling duplicate alerts, and there is no issue with `withClear` option. @jessegreenberg it seems like we shouldn't bypass that check in Property, but instead perhaps work on a work around. Do you have any suggestions?

In `updateLiveElement` it seems strange that we are sometimes setting the property, and sometimes the liveElement directly. Perhaps working on that would move us to a solution.

**Comment by zepumph** [comment]
@jessegreenberg this should no longer be a problem since we removed the Properties from AriaHerald. Can you confirm that this is fixed, and close if all looks good.

**Comment by jessegreenberg** [comment]
Yes, this is no longer a problem. I see the same alert come through multiple times in the a11y view.
