### ISSUE TITLE
Automatically generate development-mode html files

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#63]
Right now we are copy/pasting and maintaining a lot of html files for sims that are launched in requirejs development mode.  Perhaps at some point we should automate the creation/maintenance of those files so if we need to make changes we can do it in a central point.

**Comment by jonathanolson** [comment]
Generating these files with the proper meta tags would prevent bugs like https://github.com/phetsims/gravity-force-lab/issues/39

**Comment by jonathanolson** [comment]
Self-assigning, as there's yet again another change that should be applied to all dev .html files. Since chipper knows more about the dependencies now, I think it should be pretty doable.

**Comment by jonathanolson** [comment]
Added developer-meeting tag to discuss code review, testing and migration plan.

**Comment by jonathanolson** [comment]
Developer meeting: I'll add conditional-loading for together into the same file, will check with @jbphet or @samreid for review and migration.

**Comment by jonathanolson** [comment]
I had to switch the loading style to fully dynamic synchronous script loads (instead of script tags), since there were some troubles getting loading order to be consistent with mixing two styles of scripts.

Can @samreid or @jbphet review and test? The one semi-issue was that getBuildConfig was somewhat designed to be the ONLY instance. Many functions like getPreload seem like they are more of a static-style function instead, and the above code is using a slightly roundabout way of providing this. We need to generate multiple buildConfigs for the different brands/preload combinations that can be loaded.

**Comment by samreid** [comment]
I'll assign this to myself for review.

**Comment by samreid** [comment]
Here are some differences I noticed between the sim.html template and the newly generated file:

![image](https://cloud.githubusercontent.com/assets/679486/11152762/a6f68e6c-89f1-11e5-8ff5-90f725093325.png)

Does the development version need the MOTW (and special carriage return) or open graph protocol?  Should they be added for consistency?

I recommend broad browser testing to make sure the new way of loading scripts will work everywhere for us.  Seems fine on OS X Chrome, but I haven't tested elsewhere.  Here are some checkboxes of what else should be tested:

- [ ] OS X Chrome
- [ ] OS X Firefox
- [ ] OS X Safari
- [ ] iPad Safari
- [ ] Windows Firefox
- [ ] Windows IE
- [ ] Windows Chrome
- [ ] Chromebook

Did I forget anything in the list?

**Comment by samreid** [comment]
Tests look great, can @jonathanolson or @jbphet launch a newly generated html on a chromebook?

**Comment by jonathanolson** [comment]
> Does the development version need the MOTW (and special carriage return) or open graph protocol? Should they be added for consistency?

I don't mind adding the MOTW, but it only helps for loading via the file:// protocol in IE (in which case, the require.js file loading is more likely to break). That's why I didn't add it in so far.

The open graph protocol would likely point to 404s on the website for new simulations, AND it's easier for us to completely ignore strings (i.e. no title string), so I left that out.

I'll test on Chromebook.

After testing is complete, I can run the task for every runnable and then do automated testing before committing, if that sounds good @samreid?

**Comment by samreid** [comment]
Yes, sounds great, thanks!

**Comment by jonathanolson** [comment]
Tested on Chromebook (looking fine). Will be doing conversions now.

**Comment by jonathanolson** [comment]
Completed.
