### ISSUE TITLE
debug and localized versions for brand=phet-io

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#630]
Discussion with @ariel-phet and @zepumph on Zoom...

We discovered that `grunt deploy-production --brand=phet-io` is currently ignoring creation of local-specific html files.  This is being short circuited on line 914 of build-server.js, effectively ignoring the `locale` option.  It should be addressed for chipper:2.0.  

Issues:

• generation of locale-specific files should be independent of brand
• all.html file is going to be needed for debug version (based on current thinking)
• @zepumph says maybe IO should always be building the all.html file as its default file, then set locale via query parameter (instead of having an html file per locale) - but this would make brand=phet and brand=phet-io significantly different.
• nothing currently on the PhET-iO website for accessing localized versions

**Comment by jonathanolson** [comment]
> generation of locale-specific files should be independent of brand

Sounds good

>  @zepumph says maybe IO should always be building the all.html file as its default file

If this is desirable, it would definitely be possible.

**Comment by zepumph** [comment]
I spoke with @samreid about adding locale support to phet-io. We agree that the `_all.html` as the main build artifact for phet-io builds seems good. It can default to english with no query parameters, otherwise phet-io clients will be able to specify any locale that they want.

It doesn't make sense to run a phet-io simulation without a wrapper, or without query parameters. Therefore adding locale support through query parameters (rather than separate files) is much more streamlined and effective for using phet-io as a client (developer).

With this in mind, we are fine moving to phet-io brand only ever building the `_all.html` file, and never an english-specific version. @jonathanolson what will be the build artifacts in a dev build? Are `_all.html` files supported there, or should we expect just the english version?

**Comment by ariel-phet** [comment]
@kathy-phet also felt using the `_all.html` seemed reasonable for iO

**Comment by jonathanolson** [comment]
This is implemented in the chipper 2.0 branch.

**Comment by zepumph** [comment]
This is working as I would expect it. The `_all.html` is the only sim file being created for all phet-io deploys. Unassigning.

**Comment by jonathanolson** [comment]
@zepumph or @samreid, should a phet-io issue be created for:

> nothing currently on the PhET-iO website for accessing localized versions

Otherwise, everything here is done.

**Comment by samreid** [comment]
I investigated support in https://github.com/phetsims/phet-io/issues/306

Here's the issue for making the website i18nizable: https://github.com/phetsims/phet-io-website/issues/94

I'll create a new issue for documenting how to launch the internationalized versions on the website.

**Comment by samreid** [comment]
New issue created above, @jonathanolson does this issue need any more testing or cleanup before closing?

**Comment by jonathanolson** [comment]
Nope, I believe the _all feature has been tested. Closing.
