### ISSUE TITLE
dot/kite/axon test configs dont match main configs, can we use one config file?

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#638]
From https://github.com/phetsims/aqua/issues/30 @pixelzoom pointed out:

> dot/kite/axon test configs have extra stuff => or just use one config file with different deps

For instance, axon/js/config.js is
```js
// Copyright 2013-2016, University of Colorado Boulder

require.config( {
  deps: [ 'main' ],

  paths: {
    AXON: '.',

    PHET_CORE: '../../phet-core/js',
    ifphetio: '../../chipper/js/requirejs-plugins/ifphetio',
    TANDEM: '../../tandem/js',
    text: '../../sherpa/lib/text-2.0.12',
    REPOSITORY: '..'
  },

  // optional cache buster to make browser refresh load all included scripts, can be disabled with ?cacheBuster=false
  urlArgs: Date.now()
} );
```

whereas axon/js/axon-test-config.js is
```js
// Copyright 2017, University of Colorado Boulder

/*
 * IMPORTANT: This file was auto-generated by "grunt generate-config". Please do not modify this directly. Instead
 * please modify axon/package.json to control dependencies.
 *
 * RequireJS configuration file for the axon sim.
 * Paths are relative to the location of this file.
 */

require.config( {

  deps: [ 'axon-tests' ],

  paths: {

    // Third-party libs
    text: '../../sherpa/lib/text-2.0.12',

    // PhET plugins
    audio: '../../chipper/js/requirejs-plugins/audio',
    image: '../../chipper/js/requirejs-plugins/image',
    mipmap: '../../chipper/js/requirejs-plugins/mipmap',
    string: '../../chipper/js/requirejs-plugins/string',
    ifphetio: '../../chipper/js/requirejs-plugins/ifphetio',

    // PhET libs, uppercase names to identify them in require.js imports.
    // IMPORTANT: DO NOT modify. This file is auto-generated. See documentation at the top.
    AXON: '.',
    BRAND: '../../brand/' + phet.chipper.brand + '/js',
    DOT: '../../dot/js',
    JOIST: '../../joist/js',
    KITE: '../../kite/js',
    PHETCOMMON: '../../phetcommon/js',
    PHET_CORE: '../../phet-core/js',
    PHET_IO: '../../phet-io/js',
    REPOSITORY: '..',
    SCENERY: '../../scenery/js',
    SCENERY_PHET: '../../scenery-phet/js',
    SUN: '../../sun/js',
    TANDEM: '../../tandem/js'
  },

  // optional cache buster to make browser refresh load all included scripts, can be disabled with ?cacheBuster=false
  urlArgs: phet.chipper.getCacheBusterArgs()
} );
```

I tried running `grunt generate-config` and it created one just like the test config (but with different main).  So it seems that the dot, axon, kite, etc configs are stale.

I'd rather work on this after chipper 2.0 merges back to master, putting on hold until then.

**Comment by samreid** [comment]
Now that chipper 2.0 is in master, I tried `grunt generate-config` in dot, and saw the same behavior as above.  @jonathanolson can you comment whether it's acceptable for dot's config to reference things like SCENERY_PHET, or should we approach this another way?

**Comment by jonathanolson** [comment]
> @jonathanolson can you comment whether it's acceptable for dot's config to reference things like SCENERY_PHET, or should we approach this another way?

It also uses `phet.chipper.getCacheBusterArgs()` and `phet.chipper.brand`, which should be guaranteed to break things. I'm not sure if SCENERY_PHET references would break things, but it's definitely unclean. It seems like somewhat of a constraint to try to make the same "config" style work everywhere.

I guess the first question is whether `grunt generate-config` should be for things that are not runnables? As in, would the consistency of having all configs being generated be worth the effort to create something that can be customized? Presumably we'd want to list more explicit dependencies for standalone repos like dot/kite/scenery (so we could also auto-generate lists of what needs to be checked out to build things), and configs would need to be somewhat more customizable.

@samreid, what are your thoughts on the tradeoffs, and whether we should only leave runnable configs as auto-generated?

**Comment by samreid** [comment]
I copy pasted the contents of dot-test-config.js over dot-config.js (and switched deps from test to main) and ran `grunt`.  It seemed like the build went properly.

It seems like right now even sims with tests have the problem that they have two very similar *config.js files.

> @samreid, what are your thoughts on the tradeoffs, and whether we should only leave runnable configs as auto-generated?

I think it's not too crazy to have unused names (like SCENERY_PHET) in the config.js file, and `phet.chipper.getCacheBusterArgs()` and `phet.chipper.brand` don't seem to disturb the build.

If there were a clean way to merge the repo-config.js and the repo-test-config.js files it would be great, but I'm not sure how to abstract over the `deps`.

I'd love to get @pixelzoom opinion on this matter.

**Comment by jonathanolson** [comment]
I just swapped `Date.now()` with `phet.chipper.getCacheBusterArgs()` for scenery/config.js, and then the scenery playground fails to run with the expected error (make sure to use incognito, as Chrome caches the config file). That seems like a larger issue than just having unused prefix entries.

**Comment by jonathanolson** [comment]
Also that means Scenery now has 4 config files:

- config.js (the original, currently used by runtime things)
- scenery-config.js (since we need something that runs scenery-main.js, added in https://github.com/phetsims/scenery/commit/8b809abeb6fd56f1e88480c1073435775edbb650)
- chipper-config.js (I haven't used it, but it looks vestigial. @samreid can I remove this? added in https://github.com/phetsims/scenery/commit/97a27fc57cbc3c3064a737316e8608e2655de19f)
- scenery-test-config.js (since we need something to point to scenery-tests.js presumably, added in https://github.com/phetsims/scenery/commit/a52b54ffe94a6737f5baa4c7d8ec156f3b598fb1)

If repositories are going to need that many config files (at least 3, it looks like), having all of the different config "flavors" would be good. It would be better to investigate if we can just have one config (and then have code that runs after loading the config that does other things).

**Comment by samreid** [comment]
I removed chipper-config.js in the preceding commit.

**Comment by pixelzoom** [comment]
It's been awhile.  I don't recall the details of why this was an issue, why we need multiple configs, etc.  I tried to piece together the details by following references to related issues, but didn't manage to fill in the gaps.  Can someone summarize?

**Comment by pixelzoom** [comment]
I verified that the only difference between circuit-construction-kit-common-config.js and circuit-construction-kit-common-test-config.js is indeed the `dep`, which point to the main.js file.  

But I don't understand... Why does construction-kit-common have a main? (construction-kit-common-main.js)  It's not in active-runnables.

**Comment by samreid** [comment]
Sorry, bad example (cck main looks vestigial and should be removed).  I wanted to talk about the general case where a sim has unit tests.  I don't think that case exists yet--it looks like only common code repos have unit tests at the moment.  You can try the following to see the general case we should discuss:

```
cd faradays-law
grunt generate-test-config
```

Then compare the configs.

**Comment by pixelzoom** [comment]
@samreid said:
>  ... I wanted to talk about the general case where a sim has unit tests. I don't think that case exists yet--it looks like only common code repos have unit tests at the moment. ...

So we're talking about a hypothetical situation?... I'm sorry, I don't have time to spend on this now.  If it requires my attention, ask @ariel-phet and we'll see what can be removed from my plate or pushed out.

**Comment by samreid** [comment]
@jonathanolson where do you want to go with this issue?  Should we try consolidating to one config file per repo, and moving the `deps` elsewhere?  (Where would that be?) . We can keep the hand-crafted configs for common repos and use the automatically-generated one for sims.

**Comment by samreid** [comment]
Tagging for developer meeting in case @jonathanolson and I don't come up with a plan by then.

**Comment by mattpen** [comment]
I'm not familiar enough with `generate-config` to be able to offer a reasonable opinion or suggestion, sorry.

**Comment by jbphet** [comment]
IMO, the best thing to do from a usability standpoint would be to make the automatic generation smart enough to create the correct config file(s).  I'm not at all sure that it is worth the effort to do so.  If we decide to keep the current hand-rolled config files for common repos, we should add comments to make it clear that it was created manually.  Right not, the automatically generated ones have a header like this:
```
/*
 * IMPORTANT: This file was auto-generated by "grunt generate-config". Please do not modify this directly. Instead
 * please modify hookes-law/package.json to control dependencies.
 *
 * RequireJS configuration file for the hookes-law sim.
 * Paths are relative to the location of this file.
 */
```

The one for dot looks like this:

```
/**
 * Configuration file for development and production deployments.
 *
 * <author name redacted>
 */
```

Hence, it's not obvious that the latter can't be generated automatically.

**Comment by jonathanolson** [comment]
I have no strong preferences for how config files should be handled for "standalone" repositories. Generation of all of the necessary files sounds fine, but I'm not sure what priority this would be, and having 3 config files seems messy. Looking into using require() to handle the `deps` (so we only need one config) would probably be a good first step.

**Comment by pixelzoom** [comment]
Deferred to next week's dev meeting.

**Comment by jessegreenberg** [comment]
3/8/18 Meeting:

No  one has a strong preference.

@jonathanolson gave a summary of this problem: We have ~half page of duplication in our config files, causing a maintainability problem.

@zepumph was volunteered to look into this. @jbphet recommended to look into this sooner rather than later, and if it looks like it will take a significant amount of work then to bail. @ariel-phet said to take no more than two hours investigating, reaching out to  @samreid if help is needed.

**Comment by jessegreenberg** [comment]
To ramp up, @ariel-phet said it was OK to spend ~3 hours on this.

**Comment by zepumph** [comment]
I began poking into this today. I found a potential solution of how to set the deps fro multiple launch points. 

In axon there are currently two config files, one for tests and one for the main launch point. I found that it would be pretty easy for any launch point (html file) to specify its own deps before running the config through a global. 

Here is what a single, consolidated config could look like:

```js

require.config( {

  deps: window.phetDeps || [ 'main' ],

  paths: {

    // Third-party libs
    text: '../../sherpa/lib/text-2.0.12',

    // PhET plugins
    audio: '../../chipper/js/requirejs-plugins/audio',
    image: '../../chipper/js/requirejs-plugins/image',
    mipmap: '../../chipper/js/requirejs-plugins/mipmap',
    string: '../../chipper/js/requirejs-plugins/string',
    ifphetio: '../../chipper/js/requirejs-plugins/ifphetio',

    // PhET libs, uppercase names to identify them in require.js imports.
    // IMPORTANT: DO NOT modify. This file is auto-generated. See documentation at the top.
    AXON: '.',
    BRAND: '../../brand/' + phet.chipper.brand + '/js',
    DOT: '../../dot/js',
    JOIST: '../../joist/js',
    KITE: '../../kite/js',
    PHETCOMMON: '../../phetcommon/js',
    PHET_CORE: '../../phet-core/js',
    PHET_IO: '../../phet-io/js',
    REPOSITORY: '..',
    SCENERY: '../../scenery/js',
    SCENERY_PHET: '../../scenery-phet/js',
    SUN: '../../sun/js',
    TANDEM: '../../tandem/js'
  },
...
} );
```

This way we could set whatever deps we wanted before launching the config. Here is the launch point in the tests html file:
```js
    window.phetDeps = [ 'axon-tests' ];

    loadURL( '../sherpa/lib/require-2.1.11.js', 'js/config.js' );
```

It works under the assumption that the "fallback" main will be the one that is used during the build.

@samreid is this too much of a "hack"? I see this a pretty flexible because a single config file could be wired into from any number of launch points. This solution assumes that we are ok with unused config paths for some types of runs.

**Comment by samreid** [comment]
Nice work @zepumph, in my opinion, the benefit of consolidating the configs outweighs the line `deps: window.phetDeps || [ 'main' ],` and its assumptions.  Did you test these configurations?

- [ ] running a sim in requirejs
- [ ] building a sim
- [ ] running unit tests in requirejs

Also, we should run this past @jonathanolson to make sure it will work OK for scenery/dot/kite since they had different use cases and other config files (like the scenery playground).

**Comment by zepumph** [comment]
We could work to make the global object more robust, like detecting `global` vs `window`. I'll look into a few more test cases.

**Comment by samreid** [comment]
urlArg is done like so:

```js
urlArgs: phet.chipper.getCacheBusterArgs()
```

Perhaps we can use `phet.chipper.configDeps`?

**Comment by zepumph** [comment]
For almost all sims, the only change will be the following line in the config:
`  deps: phet.chipper.configDeps || [ 'faradays-law-main' ],`

Even though most don't have tests these days, this allows any other html file to use this config file. In FL it ran in requirejs and built/ran built. Then in the testing template we will just need to add a value for that global. 

I'm still a little confused about sceneryand its dependencies. I don't fully understand all uses where those config files are run, so I'm a bit more worried about a null pointer with `phet.chipper.configDeps`. Ways to proceed: (1) if the global was directly off of window (`window.configDeps`), then it wouldn't matter where it was run because it could just be undefined. (2) we could add conditional safety like `phet && phet.chipper && phet.chipper.configDeps`.

**Comment by zepumph** [comment]
Time spent so far on investigation, 1.75 hours.

**Comment by samreid** [comment]
I couldn't find any usages of axon/js/config.js, so I deleted it (I also tested that http://localhost/scenery/tests/playground.html wasn't using it).

**Comment by zepumph** [comment]
I also can't find any usages of `scenery-config.js` in the whole project, but that is needed to build scenery. Is there something that needs axon's config for somehow "building" axon (even though it isn't runnable)? If not then was it just automatically created somehow, and deleting it isn't enough?

**Comment by samreid** [comment]
I reverted to 0c6a42b99b2441d796ae5cedc1782316d874f368 and ran 

```
~/github/axon$ grunt
Running "lint-all" task

Running "clean" task

Running "build" task
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION]: axon does not appear to be runnable
  at grunt.registerTask.wrapTask (/Users/samreid/github/chipper/js/grunt/Gruntfile.js:139:9)
  at Object.<anonymous> (/Users/samreid/github/chipper/js/grunt/Gruntfile.js:85:13)
  at Object.thisTask.fn (/Users/samreid/github/axon/node_modules/grunt/lib/grunt/task.js:73:16)
  at Object.<anonymous> (/Users/samreid/github/axon/node_modules/grunt/lib/util/task.js:294:30)
  at Task.runTaskFn (/Users/samreid/github/axon/node_modules/grunt/lib/util/task.js:244:24)
  at Task.<anonymous> (/Users/samreid/github/axon/node_modules/grunt/lib/util/task.js:293:12)
  at /Users/samreid/github/axon/node_modules/grunt/lib/util/task.js:220:11
  at process._tickCallback (internal/process/next_tick.js:150:11)

Full Error details:
{
  "generatedMessage": false,
  "name": "AssertionError [ERR_ASSERTION]",
  "code": "ERR_ASSERTION",
  "expected": true,
  "operator": "=="
}
```

axon/js/config was created manually, and looks like it was originally created for unit tests in bcf214d7ad74a055806169948c67425263887399

I confirmed the scenery build is using scenery-config.js

**Comment by samreid** [comment]
I don't think axon can/should be built by itself at the moment.

**Comment by zepumph** [comment]
I think that we have done enough to recommend a solution to the rest of the devs this dev meeting.

I suggest that we move towards a single config file per repo, where the deps can be specified as a global, falling back to a default that is the same as the dependency needed to build. Example:
`deps: phet.chipper.configDeps || [ 'faradays-law-main' ],`

Points of discussion:
1. This solution works under the assumption that each repo is only built into a single product, using the config file's default `deps`, because I don't suggest adding the global into the build process.
2. What should the global be called? By nesting the above example under `phet` and `chipper`, we now need to check for nulls before proceeding, unless these configs can guarantee the existence of them. Another suggestion would be to just have `window.phetConfigDeps` on the top level of the global object.

Marking for dev meeting.

**Comment by jonathanolson** [comment]
> What should the global be called? By nesting the above example under phet and chipper, we now need to check for nulls before proceeding, unless these configs can guarantee the existence of them. Another suggestion would be to just have window.phetConfigDeps on the top level of the global object.

Sounds tricky. When the config is loaded by the require.js optimizer (in the build process), `window` isn't defined, and `global` is where all global variables live. Also `phet` won't be present for many dot/kite/scenery things. Can we detect the presence of window/global, and use something defined there (instead of something namespaced under phet.chipper which often doesn't exist?)

**Comment by samreid** [comment]
It sounds like `phet.chipper` works OK, so perhaps we can declare any global--perhaps something like `phetConfigDeps` would work?

**Comment by jonathanolson** [comment]
> It sounds like phet.chipper works OK

My above comment was mostly noting that this was not ok, and would fail in many cases where it is not defined.

Perhaps this is the breaking point, and we define the phet global in standalone (e.g. scenery) builds?

**Comment by samreid** [comment]
I don't think we need to define a `phet` global, my point was that any global defined could be accessed on the `window` or on the `global` if you leave off the prefix.  Hence a `configDeps` global (not structured under `phet`) may be ok?

**Comment by jonathanolson** [comment]
> Hence a configDeps global (not structured under phet) may be ok?

I'm kinda to the point where it feels like if we need to introduce a global, we should have whatever standalone builds of scenery/etc. have a `phet` global where we can stuff things. It sounds like it will help in general, and that the tradeoff is probably worth it now (and it will mean common code won't need to check for the presence of the `phet` global).

**Comment by zepumph** [comment]
That sounds like a nice improvement. @jonathanolson how much work do you think that would be to do? Then we could adapt the config files.

**Comment by jonathanolson** [comment]
I'll look into providing the phet namespace for standalone builds. Shouldn't take too long.

**Comment by zepumph** [comment]
After @jonathanolson finishes, I will change all config files to use this global, and only 1 config file per repo. Note this will involve adapting the sim config files via the automated config file task, but common code/scenery subtypes are manually created config files.

**Comment by samreid** [comment]
What if we just have one config.js file (lives in chipper)?  It encodes all our plugins/repo paths and is used by every project instead of us generating copies or near copies of them?

**Comment by zepumph** [comment]
In dev meeting yesterday we decided to keep a config file per repo, although there wasn't much discussion about having just 1 config file. @jonathanolson please assign back to me when you have created the global that scenery can use.

**Comment by samreid** [comment]
This got much simpler in https://github.com/phetsims/chipper/issues/1245 and there are also recommendations there for more improvements.
