### ISSUE TITLE
Dependencies seem incorrect, should be improved and updated

### ISSUE THREAD

**Issue by jbphet** [phetsims/chipper#654]
This issue originated from a discussion in the 2/1/2018 developer meeting.

Currently the `build.json` file in chipper contains the following:
```
"phetLibs": [
      "phet-io",
      "phet-io-website",
      "phet-io-wrapper-classroom-activity",
      "phet-io-wrapper-lab-book",
      "phet-io-wrapper-sonification",
      "phet-io-wrapper-visualizing-engagement",
      "phet-io-wrappers"
    ]
```
First off, it seems odd that `phet-io-website`, `phet-io-wrapper-sonification`, and `phet-io-wrapper-visualizing-engagement` are on this list, since sims shouldn't depend on the website, they don't depend on the sonification wrappers since that wrapper isn't deployed with them, and...well, I don't know much about the visualizing-engagement wrapper, but it just doesn't seem like it should be on this list.  This is causing some odd situations where lint problems in, say, phet-io-wrapper-sonification are causing all sims to be undeployable and to show up as broken on continuous test.

Second, several of the remaining dependencies are not actually dependencies for building the sim, but are instead needed for the entire build (including built wrappers) for the phet-io product.  We should consider reorganizing this to more clearly distinguish between these different types of dependencies.

This should probably be tackled in two phases.

Assigning to @ariel-phet to determine the next steps on this.

**Comment by zepumph** [comment]
As of this writing, `phet-io-wrapper-visualizing-engagement` has been renamed and is no long in this list.

I removed the sonification wrapper, because it isn't needed. Currently the phet-io-website is needed because on build we grab a snapshot of the dev guide for documentation, but there is talk of removing that as well in favor of the `phet-io-wrappers/documentation` wrapper, see https://github.com/phetsims/phet-io-wrappers/issues/68.

@samreid what do you think about separating these dependencies out into 1."needed to build the phet-io sim" and 2. "needed to have a phet-io sim, but it isn't actually bundled into that file."

I definitely understand the separation, but from a birds eye view of the building/project and an implementation perspective, I'm not sure that I see a benefit in separating the two. I'm curious to see what @samreid thinks.

**Comment by samreid** [comment]
I'd recommend to leave the dependencies combined, since they are all required to build the "PhET-iO" branded version, which includes the sim and wrappers.  When we get rid of the website dependency, the list will read as:

```
      "phet-io",
      "phet-io-wrapper-classroom-activity",
      "phet-io-wrapper-lab-book",
      "phet-io-wrappers"
```

which seems correct to me.  In the future, we can allow sims to "opt in" to "phet-io-wrapper-classroom-activity" and "phet-io-wrapper-lab-book" and others like them.

**Comment by zepumph** [comment]
I agree, to me this is exactly what we signed up for when combining dependencies. It doesn't seem too intrusive. I like the idea of an "opt-in" for the dedicated wrapper repos, but I feel like it is low priority until there are more of them across more sims.

**Comment by zepumph** [comment]
See https://github.com/phetsims/phet-io-wrappers/issues/68 for tracking the removal of phet-io-website as a dependency.

**Comment by samreid** [comment]
Since outstanding work is tracked in https://github.com/phetsims/chipper/issues/661 and https://github.com/phetsims/phet-io-wrappers/issues/68 I think this issue can be closed.
