### ISSUE TITLE
_all.html with an unsupported locale should use fallbacks

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#694]
Uses the standard fallback process for locales. Currently hard-errors, e.g. http://phet.colorado.edu/sims/html/equality-explorer/1.0.0/equality-explorer_all.html?locale=no.

**Comment by jonathanolson** [comment]
Built a sim now (equality-explorer), and it seems to support fallback properly (unknown locale => en, vi_MX => vi, etc.)

@ariel-phet, what type of testing/review should this go through? It's a moderately core part of how strings work.

**Comment by ariel-phet** [comment]
@jonathanolson I think it should definitely be reviewed and tested.

Perhaps talk to @jbphet about review, since he is the most familiar, and then we can have QA do some testing.

**Comment by jonathanolson** [comment]
@jbphet can you check the above commit?

**Comment by jbphet** [comment]
The code change looks reasonable.  I also tested this by first duplicating the issue on the currently live all_HTML file for acid-base-solutions, which is v1.2.12.  I used the locale "zz", and indeed, it failed to load.  I also tested "es_ZZ", since I noticed that the new code has a fallback for going to just the language code if the full locale isn't found (and "es" is supported for this sim).  I then built an all_HTML version of this sim on my machine and tested with "zz", and it correctly fell back to English, and then "es_ZZ", which correctly fell back to Spanish.  It appears to be working well.

In the interest of time, I didn't test string overrides.

My IDE was complaining about the lack of a copyright comment, and I noticed a few non-standard line spacing issues, so I did some minor code cleanup.  @jonathanolson - please look at these and feel free to revert if there was some reason that it was done like this.  Other than that, this should be ready to close.

**Comment by jonathanolson** [comment]
Sounds good. It probably didn't have the comment, since it gets included straight into the HTML without minification or anything. Thanks for the review!
