### ISSUE TITLE
problems with `grunt report-media`

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#710]
The task is implemented in reportMedia.js.  Problems include:

- [x] Does not support subdirectories in media directories.  This is failing for function-builder, which has images/cards/ and images/functions/.  A comment in reportMedia.js indicates that support for subdirectories was intended: `// Iterate over all media directories, such as images and sounds recursively`.

- [x] Would be nice if it didn't abort when a missing license.json file is encountered.  This happened for installer-builder/images/.

- [ ] Unclear how sims are building if this is failing, since this indicates a license documentation problem, which is supposed to prevent build.

I spent 15 minutes on this and got nowhere.  Assigning to @ariel-phet to prioritize and assign.

**Comment by pixelzoom** [comment]
For whoever gets to work on this... Documentation for `grunt.file.recurse` can be found at https://gruntjs.com/api/grunt.file#grunt.file.recurse.

**Comment by ariel-phet** [comment]
I probably need a bit of discussion to better understand priority and such. Marking for dev meeting

**Comment by samreid** [comment]
A better approach would be to delete `reportMedia.js` and move its unique functionality (of searching for stale entries in the license.json files) to run along side the license checking that already happens during each `grunt` build.  That will help us automatically track the license.json files on a repo-by-repo basis instead of having to remember (or run a cron job) a supplementary task like `grunt report-media`.

**Comment by jonathanolson** [comment]
> Unclear how sims are building if this is failing, since this indicates a license documentation problem, which is supposed to prevent build.

I don't believe this is used during builds.

**Comment by ariel-phet** [comment]
Assigning to @Denz1994 (with some support from @jonathanolson) to work on after CL:B and Masses and Springs:Basics is to QA phase.

**Comment by Denz1994** [comment]
`grunt report-media` now runs alongside build default tasks and can optionally be turned off (similar to `--lint`). The tasks also logs errors for missing license.json files or relavent files listed in the licencse.json. Subdirectories are also checked if any are present in media directories. Thanks @jonathanolson for the help. Closing.

**Comment by jessegreenberg** [comment]
Reopening, this issue may be causing failures on CT, I am noticing a number of reports like 
```
circuit-construction-kit-black-box-study : build : phet
Failure to grunt snapshot-1548281897096/circuit-construction-kit-black-box-study:
Running "lint-all" task

Running "report-media" task
>> missing-file: circuit-construction-kit-common/images/ammeter_probe.png
Fatal error: There is an issue with the licenses for media types.
```

**Comment by Denz1994** [comment]
CT failures are due to missing files for related media (images, sound, etc.) After reviewing failures in CCK, FPAF, and Projectile-Motion, the cases for missing files are because the license.json has entries for image files that don't exist.

These license.json files should be updated. @KatieWoe will make issues and assign the relevant maintainer(s) of the repo.

**Comment by pixelzoom** [comment]
I resolved all of the issues that @KatieWoe opened.
