### ISSUE TITLE
Delete duplicates.txt?

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#717]
I see that `duplicates.txt` hasn't been committed on for over a year. I often get false positives from that file while searching the project.

What is the purpose of this file currently. Can it be deleted? Assigning to @samreid because he has most of the commits in the file.

**Comment by samreid** [comment]
According to the adjacent README:

> duplicates/duplicates.txt is a record of `grunt find-duplicates --everything` so we can track duplicates over time.

The idea was to be able to track duplicates as a function of time, to make sure we are having less and less instead of more.  It is nested in a directory named duplicates/ to make it easy to exclude from your IDE search paths.  I do not know if it is at all useful.

**Comment by samreid** [comment]
I fixed the script so it can run with options again and concluded that tracking over time isn't too important, or if we decide to track over time we can use an approach like perennial/repo-report.  Hence I removed duplicates.txt.  Closing.
