### ISSUE TITLE
ensure that dependencies.json gets checked in

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#75]
Nothing in the build-&-deploy process ensures that dependencies.json gets checked in. You must remember to do so manually. And it's critical to have that file in order to do a maintenance release (grunt checkout-shas).  The current workaround is to get dependencies.json from spot:dev/html/ if you forgot to check it in.

**Comment by pixelzoom** [comment]
Rather than handle this in `grunt build`, I modified deploy-dev.sh to add/commit/push dependencies.json. So it gets changed only when you actually do a deploy. (Eventually, I'd like to see deploy-dev.sh replaced by a grunt task, but that's another issue.)

Assigning to @samreid to review, since he's been the only commenter on this issue.

**Comment by samreid** [comment]
The change sets look good.  Let's take it for a test drive.  I ran grunt then deploy-dev. Here is a commit from the deploy-dev:

https://github.com/phetsims/forces-and-motion-basics/commit/26b3ad32b1d59c9d80a7d6ea8f2e66c7f5df8836

I compared the contents of the dependencies.json in github to the one on the server and they were identical.  So everything seems great here.

The one minor issue to discuss was just the wording of the autocommit message:

> check in dependencies.json for 1.1.4

Perhaps this struck me as odd because git is about commits rather than check ins, and just thinking through what we want the file history to read like:  Perhaps reword as:

> updated dependencies.json for 1.1.4

I do like putting the version number in that autocommit though.

Reassigned to @pixelzoom for discussion.
