### ISSUE TITLE
Buffer() is deprecated due to security and usability issues

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#752]
Is this something that needs to be addressed?

```
% grunt --brands=phet
Running "lint-all" task

Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (faradays-law, brands: phet)
Building brand: phet
>> require.js optimization for brand: phet complete (3940789 bytes)
(node:25899) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
>> Minification for phet complete
>> Require.js: 1163745 bytes
>> Preloads: 242274 bytes
>> Mipmaps: 722392 bytes

Done.
```

**Comment by pixelzoom** [comment]
I see `new Buffer` in chipper, rosetta, and sherpa/lib/clarinet-1.0.0.js.

**Comment by ariel-phet** [comment]
Seems like a good quick dev meeting topic, marking as high priority so we get to and deal with it.

**Comment by samreid** [comment]
According to https://stackoverflow.com/questions/52165333/deprecationwarning-buffer-is-deprecated-due-to-security-and-usability-issues we should use `Buffer.alloc` instead of `new Buffer`.

**Comment by samreid** [comment]
@jbphet volunteered to fix the three occurrences, including rosetta and chipper.  We will leave clarinet.

**Comment by pixelzoom** [comment]
FYI, more on `Buffer()` deprecation: 
https://nodesource.com/blog/understanding-the-buffer-deprecation-in-node-js-10/

**Comment by jbphet** [comment]
The link that @pixelzoom is a good one for the history of the deprecation of the constructor.  I was a bit curious as to the motivation.  I didn't spend much time looking, but found what I thought was a decent explanation at https://nodejs.org/en/docs/guides/buffer-constructor-deprecation/ in the FAQ section.  The bottom line is that there the constructor can be tricked into allocating uninitialized memory that contains, say, password data.  It also could be used as an attack vector by causing huge memory allocations.

**Comment by jbphet** [comment]
In https://github.com/phetsims/chipper/issues/752#issuecomment-488016499, @samreid said that, "we should use `Buffer.alloc` instead of `new Buffer`".  I thought I should note that this is context dependent, and in some cases we should use `Buffer.from` instead.  See the [referenced Stack Overflow article](https://stackoverflow.com/questions/52165333/deprecationwarning-buffer-is-deprecated-due-to-security-and-usability-issues) for details.

**Comment by jbphet** [comment]
My approach to fixing this was to add debug output to the chipper files where the replacement calls needed to go, then making the replacements and verifying that the code was indeed being invoked during a build, then verifying that the build succeeded, then verifying that the product of the build ran correctly.  In chipper, there were two usages of `new Buffer`, one for encoding files such as sounds and images to base6, and another for creating mipmaps.  I focused my testing of the built sims on things related to these, such as verifying that images looked correct and that changing the size of the sim didn't cause any visual problems with images.

The change to rosetta is harder to verify, but I felt reasonably confident after making the chipper changes.  For other reasons, I plan to pull the latest rosetta changes on to ox-dev in the next few days and do some testing, so I'll keep an eye out for any problems that could be related.

Since chipper is involved, I also waited for one cycle of CT to complete to make sure builds appear to be succeeding, and they are.  

Assigning to @pixelzoom to double check and close if the changes seem reasonable.

**Comment by pixelzoom** [comment]
I can't say that I'm familiar with `Buffer`, never having used it. But changes looks reasonable to me, and it sounds like @jbphet has tested rigorously.  So closing.

**Comment by jbphet** [comment]
One last thought on this: The security risk isn't really a thing for chipper, since that code isn't being used in a server, it's rosetta where the change really mattered.  It's nice to get rid of the warning in chipper though, which is why I went ahead and did it.
