### ISSUE TITLE
Run chipper-startup.js during requirejs mode

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#769]
In https://github.com/phetsims/chipper/issues/764, I said:

> (2) Does chipper-startup.js run during requirejs mode? It appears that it doesn't. Do we want our build to deviate from requirejs mode in this way?

@jonathanolson replied:

> I don't think we ever plan to give require.js versions out to be embedded, and it would require a different solution. I have no problem with things differing, do you have a different opinion?

At a minimum, chipper-startup.js should be clearly documented as running only in built mode.  But I think it would be better to run this in requirejs mode for uniformity and make it easier to debug/maintain this phase.

Reassigning to @jonathanolson for discussion.

**Comment by jonathanolson** [comment]
Oops! In https://github.com/phetsims/chipper/issues/773 and the requirejsStartup branch, I noted an approach where the similar approach can be done during require.js mode. Does that look good?

I don't see a big advantage to it, so I'm pretty impartial. Otherwise I'm happy to document that it's a build-only thing.

**Comment by samreid** [comment]
https://github.com/phetsims/chipper/issues/773 looks great and I recommend closing this issue.
