### ISSUE TITLE
Investigate including core-js/babel-polyfill for use in simulations

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#782]
This would give us Map and potentially other useful things. Previous discussion is at https://github.com/phetsims/chipper/issues/551#issuecomment-404566209

**Comment by ariel-phet** [comment]
Bringing back up for dev meeting, in particular since we now are dropping IE 11 support, is this still relevant?

**Comment by pixelzoom** [comment]
7/23/20 dev meeting:

@jonathanolson says that this is tricky. It's still relevant (gives us some stuff), but we'd be getting less benefit.  We'd need to investigate. 

@jbphet if there's nothing that we're wanting now, should we just wait for browser support, and close this issue?

@jonathanolson is fine closing.

**Comment by pixelzoom** [comment]
Reopening.  There is some commented-out code in WilderModel.js that refers to babel-polyfill.  @zepumph will comment them back in and make sure that they work.

**Comment by zepumph** [comment]
I uncommented all of the remaining entries, which were: Symbol.iterator, Set, Map, and For...of loops, and build a version of wilder.

https://phet-dev.colorado.edu/html/wilder/1.0.0-dev.1/phet/wilder_en_phet.html

This fails with an error `ReferenceError: regeneratorRuntime is not defined` on all browsers I tested. After process of elimination, I found it to be because of `Symbol.iterator`. I couldn't figure out how to prevent that error. I tried a few things in transpile.js, like removing IE from the browser list, but to no avail.

For now, I think I'm going to give up. I will uncomment the Set and Map, and I also created https://github.com/phetsims/chipper/issues/966 to investigate using for...of loops in sim code.

So Symbol.iterator is still not supported. Closing
