### ISSUE TITLE
why do sim repos need to be added to both active-sims and active-repos?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#79]
Every sim repo that is in active-sims is also in active-repos, and it seems that this will always be the case.  (If I'm missing something, please describe an exception.) Assuming that this is the case, why do sims have to be included in both files?  It's a tiny bit of hassle, and one more place to introduce human error.

**Comment by jonathanolson** [comment]
Definitely changeable, but the current reasons are:

1. So that utilities that operate on all repos that should be checked out don't have to combine multiple files and sort.

2. We've added stub repos that can't be built in the past (see bending-light right now), and are only added to active-sims when they can be built (but we still want to update all repos and pull changes).

**Comment by pixelzoom** [comment]
Sounds like not worth the effort to change. I guess we'll just have to remember to keep adding sims to both files. Closing.
