### ISSUE TITLE
string plugin `getWithCache` doesn't really cache that much

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#797]
While working on https://github.com/phetsims/rosetta/issues/193, I found that almost every string being required from the sim was triggering a loading of the string file. I think this is because all the require loads occur before the text plugin has async come back with the JSON. 

A good way to test this problem is to put `console.log('url')` in the text.get() callback.

**Comment by zepumph** [comment]
Above I added a way to cache the intermediary state before the first loading of a string file. I'm pretty happy with this change. It is simple, and is a definite improvement in my book. @samreid can you please review.

**Comment by samreid** [comment]
This looks great and looks like it cures the symptoms described in https://github.com/phetsims/chipper/issues/730.

Some questions and comments:

* `{Object.<url:string, Array.<function>}` is missing a `>`
* Why does `action => action && action() ` check `action &&`?
* In `action => action && action() ` it seems better to pass through parsed directly like `action => action && action(parsed)`, instead of relying on the closure variable to be correct in the arrow function.  Would that work?

**Comment by zepumph** [comment]
Thanks! I really like the suggestions. How's that?

**Comment by samreid** [comment]
Looks great, thanks!  I'm ready to close if you are.
