### ISSUE TITLE
Where do common query parameters belong?

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#799]
During https://github.com/phetsims/joist/issues/576 @zepumph @chrisklus and I noticed TamboQueryParameters, which seems nice!  Instead of appearing in initialize-globals, these query parameters are declared in tambo.  When should query parameters be added to initialize-globals vs in a dedicated repo?  Should query parameters be moved from initialize-globals to more specific repos?  Perhaps many initialize-globals query parameters, such as `dev` or `fuzz` belong in joist?  Perhaps `enhancedSoundInitiallyEnabled` should be in tambo?

**Comment by pixelzoom** [comment]
> Should query parameters be moved from initialize-globals to more specific repos?

I don't feel too strongly one way or the other on this.   But I'd like to point out two downsides of having `{{REPO}}QueryParameters` for each common-code repo:

(1)  There will a _lot_ more places to look for query parameters.  Currently, there are only 3 places that you have to look: initialize-globals.js, phet-io-initialize-globals.js, and {{SIM}}QueryParameters.

(2) There will easier to cause name collisions, because it will be more difficult to determine if you're choosing a unique name (see 1). Does QueryStringMachine detect such collisions?

> Perhaps `enhancedSoundInitiallyEnabled` should be in tambo?

If `TamboQueryParameters` continues to exist, then `enhancedSoundInitiallyEnabled` (and any others that are tambo-specific) should definitely be moved there.  Having tambo query parameters in 2 different places is inconsistent and not helpful.

**Comment by jbphet** [comment]
I created `TamboQueryParameters` with the thought that the parameters were temporary and for testing/debug only, and if they every became permanent, they'd be moved to `initialize-globals`.  I'd be fine with doing away with this file and putting everything in `initialize-globals` and just marking them with a TODO or some other agreed-upon approach for parameters of this ilk if that is preferred.

**Comment by pixelzoom** [comment]
It might be good to add a TODO comment in `TamboQueryParameters` documenting your intention that it is temporary.

**Comment by zepumph** [comment]
I would be interested in hearing @samreid's response to https://github.com/phetsims/chipper/issues/799#issuecomment-537738666. I know that yesterday when he created this issue, he thought that it was preferred to have separate QP locations.

**Comment by samreid** [comment]
> Does QueryStringMachine detect such collisions?

No

**Comment by jbphet** [comment]
I've created an issue in tambo to either remove or move the query parameters once the development is further along.  I think it's safe to close this one.
