### ISSUE TITLE
investigate eslint rule lines-around-comment and spaced-comment

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#804]
We have an items in the CRC about this;

```
- [ ] Line comments should generally be preceded by a blank line.  For example:


  // Randomly choose an existing crystal to possibly bond to
  const crystal = this.crystals.get( _.random( this.crystals.length - 1 ) );
  
  // Find a good configuration to have the particles move toward
  const targetConfiguration = this.getTargetConfiguration( crystal );


- [ ] Line comments should have whitespace between the `//` and the first letter of the line comment.  See the preceding example.


```
Perhaps this could help us remove some junk from the CRC.

**Comment by zepumph** [comment]
Tagging for dev meeting because I don't necessarily have time to add this on to my list right now, but perhaps someone else would feel passionately.

**Comment by pixelzoom** [comment]
To be blunt, I feel like this would be a waste of time.

> - [ ] Line comments should generally be preceded by a blank line.  For example:

We have previous established that it's OK to violate this in some cases. That's why it says "generally".  For example in the case, there's no need for blank lines before the comments:

```js
if ( expression ) {
  // description
  statement;
}
else {
  // description
  statement;
}
```

I also don't care whether someone writes "// description" or "//description".  What is much more important is that "description" is easy to grok - the developer has taken the time to read "description" to verify that it is informative, concise, and grammatically correct.  I've done a lot of code reviews, and the number of comments that were difficult to grok vastly outnumbers the comments that were missing whitespace. 

So I would rather see us putting our time into thoughtful comment (and specifically proofreading), rather than implementing rules for identifying whitespace.

**Comment by pixelzoom** [comment]
Two other thoughts...  

These are spacing conventions. Why is it necessary to address these and not other spacing conventions like `if ( expression )` versus `if (expression)`?  Can they be addressed via phet-idea-codestyle.xml instead of lint rules? 

I'm in the habit of formatting my IntelliJ/WebStorm task comments without a space. I frequently use `//TODO`, `//REVIEW`, and `//BUG`, and they show up in the WebStorm task view. I can certainly change my habit to adding a leading space, but would prefer not to unless it's really necessary.

**Comment by zepumph** [comment]
What if we ran two lint processes each time. One without the fix option (which had most of our lint rules), and a few with the fix option, such that things like these spacing discrepancies were always the same automatically. Alternatively we could just run it once, but with the fix on, so that these issues were always auto fixed. That could alleviate some dev time in thinking about these small problems in the future. 

Note though that doing this would mean we would likely want to turn off the `fix` option when adding a new lint rule, or experimenting with new ones.

**Comment by samreid** [comment]
My preference based on aesthetics, readability and because I am used to it, is to put a blank line before line comments, and a whitespace after `//` comments. That being said, I'm happy to proceed with group consensus.

**Comment by zepumph** [comment]
The consensus today was as follows:

* The goal is to make the cognitive load as low as possible, even talking about this is likely too much cost. 
* We definitely don't want these to be lint rules
* This is really low priority
* It is not needed to have these items in the CRC.
* Some devs felt like needing a newline above comments was not always nice.
* It will likely be really easy to fix these by running lint with the fix option, and doing this on daily-grunt-work. Then we wouldn't ever think about this again.
* If automated, the CRC items (or if they live somewhere else) should be deleted.

I will make this very low priority, and see if it ever gets done. I will also note that the last 30 seconds of this discussion went from me hovering over the close button and not doing anything, to the above sentiment. I still maintain the right to just close this. Thanks all!

**Comment by zepumph** [comment]
I don't think this needs any more time. Closing
