### ISSUE TITLE
String handling for ES6 modules

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#832]
While @jonathanolson and I were collaborating on https://github.com/phetsims/chipper/issues/820, we recalled that our current build process tracks exactly which strings are loaded by each sim.  For instance, only some "scenery-phet" strings are used by "natural selection".  This information is used to present a pruned list to the translator.  

In moving forward with ES6 modules, we could save time by moving to a paradigm where we request translators to translate all strings in dependent repos, so that we don't need to trace through the program and see which strings are used in each sim.  Is our project mature enough in its translations that we can do that?  Or do we still need to compute pruned sets of strings?

If we need to compute pruned sets of strings, this could be accomplished via a webpack loader which looks at each file as it is loaded, or by inspecting the build file (without minification) to see where something like {repo}Strings[.|/[ is used.

**Comment by jonathanolson** [comment]
We need to identify used strings, we should ideally prune the strings included in a sim to ones that are used, and there's an expressed preference for short and convenient usage of strings (e.g. import a single string file, and use convenient notation to grab strings out of it).

**Comment by samreid** [comment]
With the constraints of (a) needing to identify used strings and (b) pruning unused strings, it seems like a natural solution is to try one file/import per string key.  The downsides are: (a) lots of files--one per string key and (b) no convenient usage as described in the previous comment.  But the usage will be equivalent to what we have now (not better or worse).  And maybe it will be OK to have lots of small files.  For example, gas properties has 55 string keys, so it would have 55 files.  That seems manageable.  Balloons and Static Electricity has 244 a11y + 17 main strings, which also seems manageable.  Here are some ideas about how webpack can print the list of used modules: https://stackoverflow.com/questions/29966345/how-to-get-a-list-of-all-files-or-modules-included-per-chunk-in-webpack

**Comment by samreid** [comment]
After the above commit, there is one string file per key, and translations are read from babel, and it is working in requirejs and built mode.

**Comment by samreid** [comment]
I tried `webpack --display-modules` and selected the lines with /strings/ to see all the strings loaded by acid-base-solutions:

```
acid-base-solutions/strings/acid-base-solutions.title.js
acid-base-solutions/strings/screen.introduction.js
acid-base-solutions/strings/screen.mySolution.js
joist/strings/simTitleWithScreenNamePattern.js
acid-base-solutions/strings/strongAcid.js
acid-base-solutions/strings/strongBase.js
acid-base-solutions/strings/water.js
acid-base-solutions/strings/weakAcid.js
acid-base-solutions/strings/weakBase.js
acid-base-solutions/strings/acid.js
acid-base-solutions/strings/base.js
acid-base-solutions/strings/initialConcentration.js
acid-base-solutions/strings/strength.js
acid-base-solutions/strings/strong.js
acid-base-solutions/strings/weak.js
joist/strings/termsPrivacyAndLicensing.js
joist/strings/translation.credits.link.js
joist/strings/thirdParty.credits.link.js
acid-base-solutions/strings/pattern.0label.1value.js
acid-base-solutions/strings/pH.js
acid-base-solutions/strings/liters.js
acid-base-solutions/strings/pattern.0value.1units.js
acid-base-solutions/strings/solution.js
acid-base-solutions/strings/tools.js
acid-base-solutions/strings/views.js
acid-base-solutions/strings/pHColorKey.js
acid-base-solutions/strings/stronger.js
acid-base-solutions/strings/weaker.js
joist/strings/menuItem.about.js
joist/strings/menuItem.enhancedSound.js
joist/strings/menuItem.fullscreen.js
joist/strings/menuItem.getUpdate.js
joist/strings/menuItem.mailInputEventsLog.js
joist/strings/menuItem.options.js
joist/strings/menuItem.outputInputEventsLog.js
joist/strings/menuItem.phetWebsite.js
joist/strings/menuItem.reportAProblem.js
joist/strings/menuItem.screenshot.js
joist/strings/menuItem.submitInputEventsLog.js
scenery-phet/strings/shortCircuit.js
acid-base-solutions/strings/concentrationGraph.yAxis.js
acid-base-solutions/strings/negligible.js
acid-base-solutions/strings/pattern.0value.1power.js
acid-base-solutions/strings/graph.js
acid-base-solutions/strings/hideViews.js
acid-base-solutions/strings/molecules.js
acid-base-solutions/strings/solvent.js
joist/strings/keyboardShortcuts.title.js
joist/strings/keyboardShortcuts.toGetStarted.js
joist/strings/versionPattern.js
joist/strings/options.title.js
scenery-phet/strings/keyboardHelpDialog.grabOrReleaseHeadingPattern.js
scenery-phet/strings/keyboardHelpDialog.grabOrReleaseLabelPattern.js
scenery-phet/strings/keyboardHelpDialog.or.js
scenery-phet/strings/key.tab.js
joist/strings/credits.contributors.js
joist/strings/credits.graphicArts.js
joist/strings/credits.leadDesign.js
joist/strings/credits.qualityAssurance.js
joist/strings/credits.softwareDevelopment.js
joist/strings/credits.soundDesign.js
joist/strings/credits.team.js
joist/strings/credits.thanks.js
joist/strings/credits.title.js
joist/strings/credits.translation.js
joist/strings/updates.checking.js
joist/strings/updates.getUpdate.js
joist/strings/updates.newVersionAvailable.js
joist/strings/updates.noThanks.js
joist/strings/updates.offline.js
joist/strings/updates.outOfDate.js
joist/strings/updates.upToDate.js
joist/strings/updates.yourCurrentVersion.js
scenery-phet/strings/key.enter.js
scenery-phet/strings/key.pageDown.js
scenery-phet/strings/key.pageUp.js
scenery-phet/strings/key.shift.js
scenery-phet/strings/key.space.js
```

So I think this process will work without much trouble.  I'm unclear on how this is consumed by rosetta, so it would be good to get help on that part.  But I think the build process adds a list of the string keys to the built sim.

**Comment by samreid** [comment]
I added structured strings, and tested that it works in friction by using the a11y-strings branch (with master merged in to it), then by adding a Japanese a11y string in babel, and testing in the a11y-view.  It worked great!

**Comment by jonathanolson** [comment]
We will want to have a multi-level fallback, e.g. if 'zh_TW' is not available, it will check `zh` before defaulting to the English string.

**Comment by jonathanolson** [comment]
Discussed approach: regardless of our strategy for imports, we'll still want to enumerate strings, and use getStringMap() and the current phet.chipper.strings for built sims, since including all translations can add 0.25MB and this way will be backwards compatible.

**Comment by jonathanolson** [comment]
I'd like `grunt update` or modulify to pack the strings (English and translated) into the top-level compilation-free HTML files (e.g. acid-base-solutions/acid-base-solutions_en.html in the repo) in the `phet.chipper.strings` object, so that we can use the same code path for built and compilation-free modes. This will be rosetta compatible, and will allow us to choose how we do imports and used-string detection at whatever point in the sprint we work on it.

**Comment by jonathanolson** [comment]
Current major approaches for figuring out which strings were used (and how imports work):

I'm leaning toward the "one import for each string file" method.

## One import for each string file method:

1. Find which string files are used, and which files they're used by.
2. Look up the import names in every usage (e.g. `acidBaseSolutionsStrings`)
3. Find usages in those files to determine used keys (and we would presumably enforce certain patterns)

For this approach, structured string key lookup would probably look natural e.g. `acidBaseSolutionsStrings.a11y.something`, and we would need to handle keys with special characters somehow (e.g. string keys with dashes, `acidBaseSolutionsStrings[ 'some-key' ]`). Hopefully we aren't using string keys with single quotes in them, we'd need to handle that.

## One import per string:

1. Webpack tells us which modules were used, we get the string keys from the module name.

Special characters would be complicated here, because if we can't use those in the JS filename or file path, looking up the string key from that would be complicated.

## Changing how our string system works

There may be long-term advantages to changing how babel is set up, so we could import it from a string file in the repo (or other brainstormed alternatives). We should discuss as a developer group about possibilities.

**Comment by jonathanolson** [comment]
We should discuss approaches in the developer meeting (still tagged). I believe I should be included in the implementation and discussion. Time estimate depends on the import approach taken.

**Comment by jonathanolson** [comment]
Once we have a decision (either the one-file import or one-string import methods), JO estimate is 4-6 hours, SR estimate is 4-12 hours.

**Comment by chrisklus** [comment]
CM: I like one import but misstyping a key might result in undefined instead of a failure.
  MK: Will strings be a real object, not just an plain js object?
  JO: We can make it fail out

JO: How do we want imports to look?
  CM: I don't care much about the structure of how these look. I don't want to lose validation for string keys.
  MK: There can be 100 a11y descriptions in a file, one import for the file would be beneficial

JO: I'm in favor of one import, anyone object? What should the syntax be?
  SR: direct getters
  JO: Nice, I'll go for that

**Comment by jonathanolson** [comment]
Useful information from the planning doc:

> Whenever a change in Babel happens, we should run it automatically.  We could also run this automatically like daily grunt work.  Or at a minimum, make sure this task runs during a build.
> What is our process for adding string translations to a published sim?  Is it automatically maintenance released?  We will need to make sure that is compatible.

**Comment by zepumph** [comment]
@jonathanolson and I met today to discuss a game plan for moving forward. Here is the outline for the current thought. 

## General outline
* modules load strings in the same way for build and compilation free 
* before the modules are loaded, `phet.chipper.strings` is populated with all strings that the sim will ever need.
* There is one string file per repo that is loaded, like `joistStrings.js`, which acts as an object that can be directly accessed for strings (like an object literal)
* The build process will still output `phet.chipper.strings` to be the exact same as what is currently output, so that rosetta code does not need to change.

## Details: 
**Preprocess** (grunt tasks etc that have to be run before running or building the sim):
	* creating `{{repo}}-strings.js`, which looks something like `export default phet.chipper.getStringsFor( 'JOIST');`
	* generating the dev html file loads in a list of that sim's dependencies, to be used at a later point in the process.



New type of **Preload**: (only used for compilation free runtime)

populate `phet.chipper.strings` in a string preload that loads english, then checks locale and loads zh_CN (no need to care about zh for fallback?!?!). Is this slowdown on compilation free loading worth not needing a preprocess step every time a string changes?!?! (@zepumph thinks "yes")

  * changes to initialize-globals.js. Create a function, called `getStringsFor( repo )` that loads the needed strings for that from `phet.chipper.strings` and populates a new object with the necessary `Proxy` references to enable the strict validation for strings that we are used to:

 	```js
	phet.chipper.getStringsFor( namespace ) {
	  // look phet.chipper.strings, creating whatever type of object we need for our API
	  if ( assert ) {
	    // mess with that object to add proxy assertions
	  }
	  // return that object
	}
	```

### From Sim Code:
**Import**:
import joistStrings from '../joist/js/joist-strings.js' //kinda nice

* allow inline statements with no need to make constants at the tops of files. 
* allow dot notation access and bracket when not available.
	```js
	new Text( joistStrings.my.string ) // prefer this
	new Text( joistStrings[ 'my-string' ] ) // support this (to support hyphens)
	```

* cases that will fail loadly in compilation free mode with assertions enabled (and maybe other places):

	```js
	joistStrings.stringThatDoesNotExist; // fail in compFreeAssert and fail in build (can't find string)
	joistStrings.fdsa = ...; // fail compFreeAssert
	joistStrings[ 'fdsa' ].fdsa //  lint error, prefer dot notation
	joistStrings[ 'fdsa-fdsa.fdsa' ] //  fail in compFreeAssert no periods in a string (prefer joistStrings[ 'fdsa-fdsa' ].fdsa )
	```

**Build process**: 
How to create phet.chipper.strings?
* parse each module file with regex to get a list of used strings for the sim.
* add those strings to a list that will be set to phet.chipper.strings
* This output will be the exact same as what is currently output to the sim in `getStringMap`.



We will likely work on this again at the end of next week.

**Comment by jonathanolson** [comment]
We have multiple strings that seem to prevent the naive "object access" approach:

```
AREA_MODEL_COMMON levelPrompt.oneProduct / levelPrompt.oneProduct.totalArea
GAS_PROPERTIES holdConstant / holdConstant.nothing
MOLARITY molarity / molarity.title
VEGAS label.score / label.score.max
WAVE_INTERFERENCE screen / screen.waves (+3)
```

For example, `VEGAS/label.score` will need to have `vegasStrings.label.score` return a string, however `VEGAS/label.score.max` would need `vegasStrings.label.score.max` return a string (which won't work, since we can't set keys on a string).

**Comment by jonathanolson** [comment]
I'm very curious in whether https://github.com/phetsims/chipper/issues/832#issuecomment-583877692 is a problem (we can either rename strings, or we can ditch that approach and go for another style of grabbing strings).

An additional thought is that since all of our string loading is now outside of the import system, it would be possible to grab strings through globals, e.g. `phet.chipper.getString( 'JOIST/menuItem.about' )` or use another approach.

Is keeping the `joistStrings.a11y.something` access format important enough to rename strings? Or what is a good alternative?

**Comment by zepumph** [comment]
From developer meeting this week:

* We will investigate renaming those 5 string keys (likely needing @jbphet's help). We will rename with `.text`.
* We will keep importing repo string objects with modules
* We will keep `a11y` in the accessibility strings so that rosetta can continue to ignore them until we support i18n.

**Comment by jbphet** [comment]
@zepumph, @samreid, and I discussed this and we have a plan for changing the string keys described above.  I'll set up an issue to do it and will reference this one.

**Comment by jonathanolson** [comment]
Ok, let me know when that is done, and I can remove the workarounds I added above.

**Comment by jonathanolson** [comment]
Workarounds removed, since the maintenance releases and work on sim masters are complete. Closing (will be checking sim builds)
