### ISSUE TITLE
"@param {Object} options" and "@param {Object} [config]" should be bad-text

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#859]
From slack:

Sam Reid:house_with_garden:  11:57 AM
Anybody else think @param {Object} options should be bad-text?

Michael Kauzmann  11:57 AM
What should it be instead?

Chris Malley  11:57 AM
@param {Object} [options]

Michael Kauzmann  11:58 AM
Oh I like that!

Chris Malley  11:58 AM
Similarly, shouldn't @param {Object} [config] be bad-text?  I see it 6 times.
:+1:
1

11:59
If it's a config, then it has at least 1 required field.  So the parameter cannot be optional. (edited) 

Sam Reid:house_with_garden:  11:59 AM
:+1:

Chris Malley  12:21 PM
Based on the number of occurrences (200+) of @param {Object} options .... Yes, I think it it should be in bad-text.

**Comment by samreid** [comment]
I was going to take a look at this, but saw too many occurrences of documentation indicating that an options object is actually required.  Those cases should be converted from `options` to `config`.  This issue will require the following steps:

* Looking through occurrences of `@param {Object} options` to see which ones should be converted to config.  This is sometimes indicated in a comment to the right of the `@param` declaration
* Text Query/replace of `@param {Object} options` with `@param {Object} [options]`
* Look through occurrences of `@param {Object} [config]` to see if they should really be `options`
* Text Query/replace of `@param {Object} [config]` with `@param {Object} config`
* Add `@param {Object} options` and `@param {Object} [config]` to chipper/eslint/rules/bad-text.js

@ariel-phet can you please prioritize and assign?  It should take less than an hour, and does not require any specialized knowledge or expertise.

**Comment by pixelzoom** [comment]
I fixed all occurrences that I was responsible for, see above commits.  

That still leaves 200+ occurrences, mostly of '@param {Object} options'.

**Comment by samreid** [comment]
I fixed the occurrences I was responsible for as well.

**Comment by ariel-phet** [comment]
@Denz1994 is willing to tackle this. Since a shorter project, marking as medium priority, would be good to try to get done in the next two weeks or so.

**Comment by Denz1994** [comment]
Changes above include:
- Replacing `@param {Object} options` with `@param {Object} [options]`
- Replacing `@param {Object} [config]` with `@param {Object} config`
- Bad-text.js rule to warning of the two bullets above
- Renaming options to config as I came across documentation that indicated required fields in `option` objects
- I only saw one case of `@param {Object} [config]` in `PieceNode.js` and it looks like it should be a `config` object. 

@ariel-phet Can you please assign someone to review the above changes? Perhaps @samreid since he opened the issue and brought up the subject via slack in the original message.

**Comment by pixelzoom** [comment]
@Denz1994 I took a quick look.  Generally looks good.  But in the PieceNode.js change (https://github.com/phetsims/fractions-common/commit/98b3fa5744f60b55c767faa0c84c7bd76166222d), it's nice that the type expression is now correct, but there's nothing that actually makes the `config` required.  `required` needs to be used for the required `config` field.   Ditto for many (all?) of the cases were `options` was renamed to `config`.  Do we want to address this aspect of options vs config here, or as a separate issue?

**Comment by Denz1994** [comment]
I've addressed the required config fields using `PHET_CORE.required()` in the config field. Other config objects had the required field verified via an `assert` statement (see `NucleusSpaceNode`). 

Looking at `NucleusSpaceNode` the assertion comes before the `merge` so it only considers the passed in config object, not the config object merged in its constructor.

I don't know if this was intentional or an oversight, but I've also seen this pattern in `BallsNode.js`, `ParticleSpaceNode`, `PlumPuddingSpaceNode`, and `AtomSpaceNode`. Should I refactor those instances as well @pixelzoom?

**Comment by pixelzoom** [comment]
Using `assert` to check for the presence of a required `config` field is a pattern that was used before `required` existed.  If it's not a big task, I think it would be best to replace such `assert` statements with `required`, so that we're using a uniform pattern in all PhET code.

For example, `NucleusSpaceNode` would change from this:

```js
  function NucleusSpaceNode( model, showAlphaTraceProperty, modelViewTransform, config ) {

    assert && assert( config && config.hasOwnProperty( 'canvasBounds' ), 'No canvasBounds specified.' );

    config = merge( {

      // a11y
      tagName: 'div',
      labelTagName: 'h3',
      labelContent: observationWindowString,
      descriptionContent: nucleusSpaceDescriptionString,
      appendDescription: true
    }, config );
```

to this:

```js
  function NucleusSpaceNode( model, showAlphaTraceProperty, modelViewTransform, config ) {

    config = merge( {

     canvasBounds: required( config.canvasBounds ),

      // a11y
      tagName: 'div',
      labelTagName: 'h3',
      labelContent: observationWindowString,
      descriptionContent: nucleusSpaceDescriptionString,
      appendDescription: true
    }, config );
```

**Comment by Denz1994** [comment]
The above suggestion was applied to deprecated assert patterns found during refactoring. There isn't anything left to do for this issue, so I'll close. Thanks, @pixelzoom for your input.
