### ISSUE TITLE
grunt tasks for deploying sims

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#87]
We currently have a bash script (deploy-dev.sh) for doing dev deployment. And production deployment is done by manually setting up directories on the server and manually scp'ing files.  It would be nice to have these grunt tasks:

deploy-dev: builds and deploys a sim to spot

deploy-prod: builds and deploys a sim to both spot and figaro

**Comment by pixelzoom** [comment]
"grunt --help" shows tasks `deploy-dev` and `deploy-production`. Is this done? Assigning to @aaronsamuel137 for comment.

**Comment by aaronsamuel137** [comment]
deploy-dev:

Deploy-dev works in some cases, though the library used has some strange behavior with regard to setting permissions sometimes, and in general doesn't seem to work with windows. Currently, it works great for me and I use it, though I think most people are still using the shell script. There are a few options here:

The easiest solution is to make ```grunt deploy-dev``` call the command line scp. This would require entering a password as before. If we want to mkdir too, it will require entering your password twice. Or you could set up an ssh key to avoid entering your password. If you have a key setup on your computer, just add your public key to ~/.ssh/authorized_keys on spot.

Any thoughts about this approach?

deploy-production:

This is currently set to deploy to phet-dev instead of figaro. I was waiting for code review/more student testing to deploy it on figaro, but perhaps I should just deploy it so we can start using it and iron out any last kinks as they come up.

**Comment by samreid** [comment]
I'm inferring that calling the command line scp would (presumably?) work well on windows.  If so, that seems like a nice general approach.  But can you note which library you used and how you selected it?  Are there other 3rd party scp/ssh libraries we should look at first?  Even if so, using command line seems pretty safe.

**Comment by aaronsamuel137** [comment]
I used scp2 - a library based on a module ssh2. Almost all modules I came across were likewise based on ssh2. I selected this because it seemed like the simplest one that was (supposedly) cross platform.

I also noticed that scp2 uses an outdated version of ssh2, and that some bugs seemed to disappear when I upgraded to ssh2. I created an issue here: https://github.com/spmjs/node-scp2/issues/37. However, I am still not sure all of the issues will be fixed by this upgrade.

I also looked into a library module node-scp, but it requires ssh key authorization and doesn't really do anything that spawning an scp process won't do. I didn't see many other options out there, but it is possible I missed something.

I am leaning toward the command line option. We could have a parameter --mkdir to indicate you want to mkdir in the cases where it is needed. That would save you having to enter your password twice unless necessary.

**Comment by pixelzoom** [comment]
Having a grunt task that calls deploy-dev.sh seems a little redundant. Might as well just beef up the shell script and skip the grunt task, unless the grunt task is doing something the shell script can't.

Are there alternative scp libraries?

**Comment by samreid** [comment]
> Having a grunt task that calls deploy-dev.sh seems a little redundant.

It would just call bash `scp` not bash `deploy-dev.sh`.

**Comment by aaronsamuel137** [comment]
And it would also mkdir and create the .htaccess file if necessary. It would just do so with bash commands instead of a library. It would also import the username, dev-server name and path (or default to spot) from build-local.json.

> Are there alternative scp libraries?

I didn't see many other options out there. The main ones I see are:

1. https://github.com/mscdex/ssh2 - we could create an scp function with the ssh library that scp2 used. Seems time consuming and redundant
2. https://github.com/ecto/node-scp - this one is so simple it provides no advantages over just spawning a scp process (this would technically use sftp not scp)

The only reason I didn't use bash scp from the beginning was that I wanted something for the build server that didn't require entering a password. However, I have since realized that setting up an ssh key avoids this problem.

**Comment by pixelzoom** [comment]
Thanks for the clarification. Sounds like calling bash commands is the way to go.

**Comment by aaronsamuel137** [comment]
These tasks have been updated. I'll wait until they get some testing before closing. I think @jbphet mentioned he would be needing to use both grunt deploy-dev and deploy-production in the near future.

**Comment by samreid** [comment]
I tested grunt deploy-dev a few times and had a positive experience.

**Comment by aaronsamuel137** [comment]
All of the issues here seem to be smoothed out now. Closing
