### ISSUE TITLE
Phet menu rather than phet-io menu

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/chipper#892]
For https://github.com/phetsims/QA/issues/482
When looking at the phet-io simulations (linked from the wrapper etc.) they seem to have the phet brand logo rather than the phet-io logo to open the menu. The loading screen still has the phet-io brand.
![notphetio](https://user-images.githubusercontent.com/41024075/75283989-27754680-57d1-11ea-857f-8eef9cbf08aa.png)
vs
![opposedto](https://user-images.githubusercontent.com/41024075/75284011-2e03be00-57d1-11ea-8802-ccc37f7a8191.png)

**Comment by jonathanolson** [comment]
This... may have been fixed by changes not related to what I did in chipper... https://phet-dev.colorado.edu/modules-testing2/molarity/phet-io/molarity_all_phet-io.html?postMessageOnError&phetioStandalone seems to look good, but https://phet-dev.colorado.edu/modules-testing/molarity/phet-io/molarity_all_phet-io.html?postMessageOnError&phetioStandalone looks buggy. Can you confirm?

**Comment by KatieWoe** [comment]
Confirmed with those links. I'll post again if we find anything while testing the new builds

**Comment by jonathanolson** [comment]
Thanks!
