### ISSUE TITLE
revise Webstorm phet-info/ide/idea/phet-idea-codestyle.xml to include organizing imports and adding a file suffix

### ISSUE THREAD

**Issue by chrisklus** [phetsims/chipper#898]
From meeting with @zepumph and @samreid.

**Comment by chrisklus** [comment]
@zepumph will mark this for developer meeting after completing so we don't have someone forget to change their own xml.

**Comment by zepumph** [comment]
Here is what we're thinking:
* When comparing the checked in code style to mine it is a bit different, perhaps that is because I changed things, and maybe it is because the codestyle is a bit out of date.
* We will want to add (at least) two things, auto sort imports, and make sure to include `.js` suffix (for windows. I'll brainstorm others.
* I will try to do small commits as we go to update the codestyle xml.

**Comment by zepumph** [comment]
@jbphet also found Editor -> General -> Auto Import which may be interesting (perhaps developer discretion). It is not, as far as I can see, part of the code style.

**Comment by zepumph** [comment]
Committed above. All devs using a jetbrains IDE should do one of the following to support proper es6 module imports:

1. pull phet-info and import phet-code style again.
2. In the settings go to `Editor -> Code Style  -> Javascript` and make sure that the following three elements are checked under the "imports" tab:
  * Use file extension in module name
  * Sort imported members
  * Sort imported by modules

Happy coding!

**Comment by samreid** [comment]
@chrisklus made changes to this, marking for meeting:developer for PSA.

**Comment by pixelzoom** [comment]
3/5/20 dev meeting:  PSA delivered, thanks! Closing.
