### ISSUE TITLE
{{REPO}}.title convention for sim title string key

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#919]
Because of the chars that we allowed in string keys, all of our sim titles now require ugly bracket notation to access them.  E.g.:

`simulaRasaStrings[ 'simula-rasa' ].title`

Converting the repo name to camelcase seems nicer, e.g:

`simulaRasaStrings.simulaRasa.title`

...but fails `grunt`:

```
% grunt
...
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: missing entry for sim title, key = SIMULA_RASA/simula-rasa.title
  at module.exports (/Users/cmalley/PhET/GitHub/chipper/js/grunt/buildRunnable.js:123:3)
...
```

I suspect that other non-sim code (Rosetta? website? wrappers?...) may also rely on the `{{REPO}}.title` convention.  And if we changed this convention, we'd likely need to maintain backward compatibility.

PhET may have other string keys that contain illegal chars. They would require the bracket notation, and I don't think we should change them. But using this as the convention for sim titles now seems odd.

Do we want to do anything about this?

**Comment by pixelzoom** [comment]
Brought @ariel-phet up to speed via Zoom.  He asked me to mark for dev meeting.

**Comment by chrisklus** [comment]
From 4/2/20 dev meeting:

We deferred until @ariel-phet returns so we can discuss it with him.

**Comment by samreid** [comment]
@zepumph points out that many places use this string key, including rosetta.  @pixelzoom questions the value of making such a significant change.

@zepumph reminds us that we should no longer add hyphens into our string keys.  In this case we are "locked in" because some repo names have hyphens.

@zepumph says we could assert that we don't have hyphens.  
@jbphet says probably not worth the effort going back to older sims.  We would probably notice that strings['..'] notation is ugly and not do it anyways.

Closing.

**Comment by samreid** [comment]
We also discussed factoring out the sim title from every main.  Joist could auto-look up the repo name from package.json and the string harvesting engine could auto-add the sim title.  However, we agreed the existing boilerplate isn't hurting us too much.  Still closed!
