### ISSUE TITLE
shorten generated phet-io api file names

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#931]
This was requested by developers. the `phet-io-elements-` is redundant, as they are already in the `phet-io/` dir. 

@chrisklus do you think you would be interested in taking this on? I would probably just be a matter of deleting all the files, then changing the prefix name in the grunt task, and then running grunt update on everything again.

**Comment by chrisklus** [comment]
@zepumph and I decided on `sim-name-overrides.js`, `sim-name-baseline.js`, and `sim-name-types.js`. Committed above. I forgot that these files names are also in the development html of every non-phet-io repo too, so I `grunt update`d all of them after handing the phet-io ones.

I messed up by deleting all of the overrides files instead of individually renaming the ones that had content. To fix, my process to identify missing overrides was go through all of my commits titled `Rename and regenerate phet-io baseline files` and save any repos that had content in their overrides files. I did that two separate times and got the same seven repos both times. Then I copied the deleted file content to the newly named override file for each one, regenerated the baseline, and then committed. @zepumph I was going to do this via my local history like we talked about but even when going back to yesterday's history, my WebStorm was confused and showed all of the overrides files as their new name and empty, so that was no help. 

@zepumph would you like to review? Relevant commits are https://github.com/phetsims/chipper/commit/56cb55082b5b5f4316b7db1f01433846c982791f, https://github.com/phetsims/phet-io-wrappers/commit/5ae070afc78497d61805f310ec4c8c0d9d21473f, https://github.com/phetsims/studio/commit/50c172da9ab4946c65137b0c0a73c86c2c3fd6e5, and https://github.com/phetsims/phet-io/commit/39517cfd5ffc0ebf08b1368689e17ccf138aa098. Other than that, looking for anything I missed might be easier than looking over a bunch more commits.

**Comment by zepumph** [comment]
Looks great!
