### ISSUE TITLE
Remove IE 11 from transpile.js

### ISSUE THREAD

**Issue by chrisklus** [phetsims/chipper#963]
From https://github.com/phetsims/chipper/issues/954 - now that we have an Error page in place that loads in IE, we should be able to remove `'IE 11'` as one of the target transpile browsers. Adding this issue to the list in https://github.com/phetsims/tasks/issues/1037 and marking for developer meeting.

**Comment by Denz1994** [comment]
From Dev Meeting on 07/16/20:

**Discussion:**

The IE dialog will run but so will the sim and possibly run into errors. Getting rid of the transpile option for `IE 11` will cause the sim not to run for IE. The IE dialog should still run as expected because its script is executed first.

@mjkauzmann Transpiling for IE will fail at some point in the future. To prevent having to deal with this in the future, let's remove the transpile option right now.

@chrisklus will investigate what targets will transpile back to ES5.
@samreid If we remove transpiling to ES5, then the build output would most likely be smaller.

@chrisklus @zepumph: This will also handle transpiling to ES5 for other platforms (i.e. mobile).

**Resolution:**
Removing the option to transpile to IE 11 will most likely make our footprint smaller and gives us performance benefits. We should remove this option.

**Comment by zepumph** [comment]
@chrisklus also mentioned worry that the lack of compiling in xhtml may eventually cause the dialog to not show. It would be good to double check on that. Let me know if I can help.

**Comment by zepumph** [comment]
A few more thoughts:
* Please note that currently the           '> 0.5%', in `transpile.js` still covers IE (with ~1.4% global usage). I'm not sure how we can get around that if we are trying to have a smaller (es6-sized) build-artifact.
* Ideally we would have the IE dialog code run through a separate processs, that isn't the main `transpile` code, so that that file, like everything else in our project save the IE dialog can be developed and maintained without thinking about IE.
* Knowing what we know now, perhaps it makes the most sense for the javascript for the IE dialog to be in its own file, then we can either document heavily that this file needs to run in IE, or set up our own transpiling for supporting IE and apply it to that file. 


Good luck! Let me know if I can help.

**Comment by chrisklus** [comment]
@samreid and I looked into this together and were able to determine the babel platform options that kept the transpile output as es6. Our current options are:

```
'> 0.5%',
'safari 9-11',
'Firefox ESR',
'IE 11',
'ios_saf 11'
```

>Please note that currently the '> 0.5%', in transpile.js still covers IE (with ~1.4% global usage). I'm not sure how we can get around that if we are trying to have a smaller (es6-sized) build-artifact.

We were able to bypass that by changing 'IE 11' to 'not IE 11'. We also needed to drop Safari 9:

```
'> 0.5%',
'safari 10-11',
'Firefox ESR',
'not IE 11',
'ios_saf 11'
```

The resulting `_en_phet.html` build file for Energy Forms and Changes was 3.45 MB compared with 3.50 MB from the original transpile options, so not much change there. There was some excited load time improvements though, at least on Chrome. Note that a different measuring procedure was used for each platform, so absolute times should only be compared within columns of the same platform. All times are in milliseconds except the iPad recordings, which are in seconds. Tests on desktop browsers were conducted in an incognito window with dev tools open.

| | es5 Mac Chrome | es6 Mac Chrome | es5 Mac Safari | es6 Mac Safari | es5 iPad Safari | es6 iPad Safari |
| ----- | ----- | ----- | ----- | ----- | ----- | ----- |
| test 1 | 2614 | 1588 | 3395 | 1398 | 2.45 | 2.58 |
|test 2|2597|1515|3235|3042|2.99|3.33|
|test 3|2643|1532|3238|3087|2.53|3.46|
|test 4|2647|1466|3300|3124|2.78|2.86|
|test 5|2595|1573|3392|3133|2.6|2.99|
|mean|2619.2|1534.8|3312|2756.8|2.67|3.044|
|mean/es5 mean|1|0.59|1|0.83|1|1.14|

Before proceeding any further, we thought we should discuss with @ariel-phet, possibly at dev meeting, if we are able to drop transpiling for iOS/Safari 9 since it's this is the last platform keeping us in es5. We found that the website says we support iOS 12+, but we also found an entry for iOS 9 (iPad 2) in the most recently updated QA testing matrix.

**Comment by ariel-phet** [comment]
@chrisklus that is fine, for a long time we had been just checking that sims opened on iOS 9 since we know there were lots of app sales long ago on iPad 2. Natural Selection (even before this transpile question) was going to break on iOS 9 anyhow, and we were fine with that.

You can definitely drop iOS/Safari 9 and I will inform @KatieWoe to remove it from the test matrix.

**Comment by chrisklus** [comment]
Safari 9 and IE 11 have been dropped. Built sims are now in ES6. Marking for PSA at dev meeting.

Note: One thing I'm not sure about - looking through some built output, there are clearly classes and arrow functions, but it looks like `var` is replacing `let` and `const` still. This does not go along with the test output that @samreid and I were trying with this babel tool when using the same targets as in `transpile.js` (see "Browsers" in the lower left): 

https://babeljs.io/repl#?browsers=%3E%200.5%25%2C%0Asafari%2010-11%2C%0AFirefox%20ESR%2C%0Anot%20IE%2011%2C%0Aios_saf%2011&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAEASCmIQHsDeBfAUJ4yB2EALtABaIrQC80AFAJRUB80ABmUsiwNzY75HQAnsirQA5GK5A&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2%2Cenv&prettier=false&targets=&version=7.11.1&externalPlugins=

Perhaps it not a big deal, but the inconsistency seems strange.

**Comment by chrisklus** [comment]
From 8/6/20 dev meeting:

SR: Do wee need to update iOS store listed support?
AP: No, we already did not support iPad 2.

Assigning @KatieWoe just so you're aware - there is some newer code running in built versions for whatever the next dev or RC version that's created.

**Comment by zepumph** [comment]
@chrisklus can you please recommend how to proceed with this issue?

**Comment by zepumph** [comment]
I'm worried that this is a high priority issue. @chrisklus can you comment on the current state of this issue? Are processes set up so that RC testing is testing this feature on IE11?

**Comment by chrisklus** [comment]
@zepumph assuming sims have been launching on all of our supported platforms, this issue is complete.

>Are processes set up so that RC testing is testing this feature on IE11?

Were you referencing this issue? https://github.com/phetsims/chipper/issues/954.

It was tested on IE 11 at the time of development. Perhaps it is worth a spot check. I'll open a separate issue.

I'm inclined to close here.
