### ISSUE TITLE
`grunt update` does not `git add` files that it creates

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#995]
`grunt update` does not `git add` files that it creates.  For example, if I add `"colorProfile": true,` to package.json and run `grunt update`, it creates `{{REPO}-colors.html`.   But then I have to remember to manually `git add` it (either via command line or IDE).

Assigning to @ariel-phet to prioritize and assign.

**Comment by jonathanolson** [comment]
It seems like the convention for scripts is to create/modify files without `git add`. This seems beneficial, since I wouldn't expect tooling to do that. This would also apply to things like generating READMEs, simula-rasa copies, updating copyright dates, etc.

If we're not doing it for all cases I'm aware of, is there a specific reason we'd want it here? I'm skeptical that this change would be helpful.

**Comment by ariel-phet** [comment]
Since there are some differing viewpoints here, it would be good to get a consensus at dev meeting.

**Comment by zepumph** [comment]
We feel good to close this, and not `git add` files from tooling.
