### ISSUE TITLE
Investigate Yarn 2

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#998]
Inspired by https://github.com/phetsims/chipper/issues/997, I decided to create a dedicated issue about investigating yarn.  As mentioned in that issue:

> yarn 2 can work completely offline and supports a global cache, which may also solve https://github.com/phetsims/chipper/issues/383.  It apparently also has a more deterministic way to pin dependencies, which we discussed in https://github.com/phetsims/chipper/issues/114

Let's touch base in developer meeting.

**Comment by Denz1994** [comment]
Just noting here 12/10/20 1:15 pm MT (mid phet-io meeting), Github Universe is presenting on the 2021 [roadmap for npm](https://githubuniverse.com/github-loves-npm/).

I've been using yarn 1 and npm simultaneously (based on [recommendation](https://www.electron.build/#installation)) in Weddell with no issue, so perhaps we can just integrate Yarn 2 where there are gaps in NPM support.

**Comment by samreid** [comment]
I'm confident I could use Yarn for my local development, the question is whether it poses a significant enough benefit that we would change our toolchains to use it instead, like when `grunt checkout-shas` or `grunt checkout-master` runs `npm prune` and `npm update`--could be easily and safely upgrade that to use yarn?  Or does the expected risk outweigh the expected benefit?

**Comment by samreid** [comment]
Developer meeting:

@jbphet this hasn't been a problem for me.
@zepumph: Is yarn better than NPM?  Should we use package-lock.json?
@samreid: My primary motivation was about improved speed and convenience, not necessarily about pinning versions or other features.
@pixelzoom: I agree, let's defer
@samreid: This may be much more significant when dealing with maintenance releases, to make things much faster.
@zepumph: I see savings in Maintenance Releases, CT.  I'm not sure how hard it would be to make sure everything can run on yarn.

Let's run this past @jonathanolson for recommendations.

**Comment by jonathanolson** [comment]
It looks like it's easy for some of us to switch to yarn, based on the documentation.

I see two benefits:

1. Speed, both for developers (on updates, but also more significantly maintenance releases), and also speeding up things like CT and our build-server.
2. By pinning dependencies, it adds extra reliability so that a new npm package break won't ruin sims production deployments (which is possible currently).

However, since our tooling uses npm, switching that would presumably require fallback detection (so we would need to use npm if yarn doesn't exist)

So... not the highest priority, but there's a chance a translation will deploy a completely broken version of a sim sometime, and it would make maintenance releases SIGNIFICANTLY faster.

**Comment by samreid** [comment]
Avoiding breakage during a translation and speeding up maintenance releases sound really great, even if we have to add fallback logic for detecting if a sim should use npm or yarn.  But on second thought, if we start yarn in master today, it could be a long time until all sims get redeployed with yarn.  Maybe we should investigate whether npm has a local cache strategy.  And to solve the breakability during transltion, maybe we should pin versions with npm.

**Comment by zepumph** [comment]
>Maybe we should investigate whether npm has a local cache strategy.

I poked around on the internet while discussing last dev meeting and didn't find anything, though there are some untrustworthy side projects on npm like https://www.npmjs.com/package/offline-npm (it isn't maintained).

>How hard would it be to do a maintenance release to get everything using yarn, or possibly a new npm strategy?

Not sure. The majority of the usages of 'npm' on master are `npmUpdate`, `npmCommand`, `execute( 'npm' . . . `, or doc like 'npm update'. Perhaps it wouldn't be too hard to update our tooling on master for it. 

It may be the kind of thing that is so low level to our sims, that only a few, consistent lines of code across all our old versions need to be changed to get things running. I'm unfamiliar with yarn though, so I don't know what the spin-up process for it would be.

**Comment by samreid** [comment]
I tried clearing node_modules and running `npm update` vs `yarn` in chipper and found yarn was about 2x as fast.  Yarn still had to build packages and link dependencies, which is why it wasn't instantaneous.

yarn: 15.83 sec
npm update: 28.94 sec

**Comment by liam-mulhall** [comment]
In https://github.com/phetsims/rosetta/issues/283#issuecomment-1179347287, I wrote up some notes on Yarn that might be helpful here:

# Overview

* Started in 2016 at Facebook as replacement for NPM.
* Goal was to create more secure, stable, and efficient package manager.
* Initially added features NPM didn't have.
* NPM has since implemented some of these features.

## Killer Features of Yarn

* Generally much faster than NPM.
* Much better support for de-duplicating packages in monorepos.

## Yarn V1

* Yarn V1 is more akin to NPM than Yarn V2. It uses a `node_modules` directory and one or more `package.json` files.

## Yarn V2

* By default, V2 abandons `node_modules` in favor of `.yarn/cache`.
  - **Q: Why does it do this?**
  - A: `node_modules` is huge, and it negatively impacts the performance of the package manager.
  - **Q: How does Yarn V2 resolve dependencies?**
  - A: It has a file called `.pnp.cjs` that contains two maps: one map links package names and versions to their location on the disk, and the other links package names and versions to their list of dependencies.
* This new scheme allows for "Zero Install".
  - **Q: What?**
  - A: Configure PNP to resolve dependencies via the `.yarn/cache` directory rather than the `node_modules` directory, and check `.yarn/cache` into version control.
  - **Q: Wait, isn't that the same thing as checking `node_modules` into version control?**
  - A: No! To give you an idea, a `node_modules` folder of 135k uncompressed files (for a total of 1.2GB) gives a Yarn cache of 2k binary archives (for a total of 139MB). The `.yarn/cache` directory contains exactly one (compressed) file per package, as opposed to `node_modules`, which contains a gigantic amount of files.

**Comment by samreid** [comment]
I would rather close this and put our effort into https://github.com/phetsims/chipper/issues/1272, closing.
